---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fuzefront-registration
  namespace: fuzequality
spec:
  encryptedData:
    token: AgAxCnCfMR/3w3ct5lkBummVinwFF59+RJX+0gjXoD9qrXE1vRpt3pJ+Sgi2/9jKwBgPpKuPi6xCn4wQRWJr9gkNUISGiYSl+qRew0UtJSSG08dHMPDL2orq0XrBtzJsQ3LuBSxSgT+S8e5598drPBKlVx/Y2Gb07fGxLCTddYt/iCwaiWA/VZQfVlxeie5eMGIIhwcDGoydRHjc1GKApRTN9OOGSelSCQogj+ARn83P3wlvUnN8+mOhPBvuoaXOTiWx6O6glCmKaLdoCYasYklUFdltiWTUR5Wf1elUrnZJ5VQlMmtJ8E+wNfUyfahlTI2q4aru5d0I+FftqWgxqXLc/07A/NCevWRKn/zc8he70h8entA/x5xZrRJialqE0VeXZeIGlVqKhwq0lfFKGlwuT87KvcmNZua1sNxKZftNruYHuwvW9MtN2wWGAKjfX/ZD0Gk5p3MMmdBwemjl6lZcAR3psCJUXWaM1FTVuApECDv3NQBhKE82xdyE5DGhq0FpsLLOClWTf7XWwzCvcwN5kh5tIkRDtclqHgBOfmIUKNyqI9tLeSnTPN/GK+lOjS2v0FwepseL2PQjzrWRZlFFifX7aAgpSlSNvYVjb3uyi5mMVVlY7hKanPJM+5YD+E+VXZR5+mBIlA6QBEvnGSPCqc+d2uGcNEw5LlTcq7q+4tYhtDMRUbcjRYfUjTHRGY44n2t9uEiGeXZiQMl9XDjE0STwoLzUPwD4cI/ynGoNj/cbjFNVfwRFshVtk8mjUXEkIbVsaUtTnbf1o7+IRVW/
  template:
    metadata:
      creationTimestamp: null
      name: fuzefront-registration
      namespace: fuzequality
    type: Opaque
