---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fuzefront-registration
  namespace: fuzequality
spec:
  encryptedData:
    token: AgA1r+LXivRDMSLvT8Xj+FjXmeaSCV0MXRlPkSOjo8BhYV1zRBg5MC9IhyqzPXapGml1AAflrNB9wtYafpLeYVxhL/vQC8pNgDFSpUWPfRCXrMe1yCuA/3Fcpg6w3yElj8omMPwbSBTec7WVjGzlHGLpnzq9zBeg9eA8++s011VihAYaONY88vk06yt/OfKn75blnVsU7zodsoOmykY4tNGrXmwE6emWnYeKOr0kyYxEW7FVmoDjIwELrL24bNDOKsOTkTSu6LCMPV3lwvG0Fjfc35WRYXYvJdf+OcuPCXXUscijMpLb8nf+VUz7AgpwH+u2RyW9k2bfctZLTSTVaB9mCSHTaOB6c+sb25WCoWHYlKXsRUlTPvYmyP5Np5X+OV2sx9ooS9b7iN4ccuKXeD7lnQJLX6HbiJIpfyuc+HW5XKBZURRg5ZII4Vqraq9yqQa+r42s+mqhUx4I3zZoKufumAqxTtYH9owtj7vNr9OfJrCrxOvrU6pIZG0X+X6SmnJVE/3HH51A+3FMoXhDWi7IgkNYmrLd3EMt5DiIjwG+m6tZm2qc5X1Tygo12ac47NP4g1CsK3uVJp7GWPrevvhogkEJx8pOwUifBi4BIjyGkcOoeLswLdnB1MXNDZKW5Ftho/1NJgniKywZVeyl5kMgWegdVH6DERGR1e+w3AfKQlCoLOIzdvYSEpTYH73wdlNQfMmZpwXkwp2Fin2Eh5F80mqAdGPwHHj20MjVvoENFCKGf5cf1P/myXeF2/XXDwtXBXkNV2bh9wipDqwfB6jH
  template:
    metadata:
      creationTimestamp: null
      name: fuzefront-registration
      namespace: fuzequality
    type: Opaque
