---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull
  namespace: fuzequality
spec:
  encryptedData:
    .dockerconfigjson: AgCZQYXd9PTSTftY/3saLHdkRr89MhTaz0vlD3t6AfdXUIsEIBzPVimP6Xe1Smrw0Jkib8ujCj670qyCd2nDogDyTD3IjTUqZeLxdXD41WKY2h+l6TLFRdsKYFlL23H7JG0iQq1OgNGx6FAPUaLa72NqiOTEWiWgdjXQ8BrqzqP+oxeWBsCq657ZyuD4rnTeDihwqJp+GK1DQ9y6hRCEyzgM8uMKCRMbDodXcoLlM1aUgOwD3dxKs8kTT+2x/cdO1iJmwYSAslG3MgYv3vHaaKt8XT/Hu/c9dtfcnLOCmUBST/svNNO/KGtVuz4bUiHi/7RNwXux/RiClT33prA4kKWFg9Cb8AsU4bXdf+48FcIrUXClHemSfqm/1oDlRqRgvmRccrRiyx2yUZKzkVDYCiJyFJ8hi+dOlySqCeUHRtZWk92plC7tugN/C6ytPdYMTgAuOGp6MOoYRTxtzEUjL6qIlrRrwaX86LlfNLAcfp4emktgEf9IjxFevtOxEpuzAOH6bDynTlWQPA7FIzznp0a9s8SSz8TpGPVLZ6TUCcaXSQnxrnKcJU+lon3tla6SJoihKrsUB1EfVYBpqrbBqdLBqkvR0SMhyuWb63xE3uvdr3/JZ1hN94Fz+BgPAleJQjobQ6YqJBvnuU8UyuUD48OGADHiT8lnG2HHALga7gRDmF4+GLM7fD+bMGUrPxaGJdEMZooPbHCSdKKuHeY=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      creationTimestamp: null
      name: ghcr-pull
      namespace: fuzequality
    type: kubernetes.io/dockerconfigjson
