---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull
  namespace: fuzequality
spec:
  encryptedData:
    .dockerconfigjson: AgA0M/IBD8VW5GYgk4WnKk1Fe2uIZbqKTnYEPsgXCTDyo4z2C9ZVjafpEf8eNWPvSFwWiv8bOm1hyK6BcQ0T5wLWivVsEB7UbZDgh6gvzTG7dXn0/NqMnpf1DuvyOnongGgKAfLFMqOuZttUIcNhHdaRpsA8oy1hvMFxtIpnUnU43sBHl8YUbShJOm33BFWkyUwhgO8NzL1ImhbRB+jJA5klm4nvRdCsc1Q+yzovOYSbJgH1av4m6GB3tQuge9w/ywyDzwAMXJegt0IWeJJTwz4JjpTQAbSMfU8bs49//PmYpnJLYmh/bPE9Jz4ScUnB7V7swjhbiK77xtRqLzRpLj/oYjng9PVtRy1Y/ZlcpI97eE2rWuXRcSGJnsatpQo7vk9ZI4xmgn+fkyXU1rLTPqzvaokNqJipr3rM6n9Ft4qmd2mZ74nDQrePpu0FBQd/timMuvTK7sGptmOy+g0J5iLHjGmTJSepLvt1d+zS6oydszapMfGTRaCvfacyO2YUXMx9qjnDw0MTBcVIZe3R8fI+lcKDRgEAHhql7NXoUZPamSUhjJDXqorvvrscfNBzVLnmKW3LoQUN4PqTb+gV4hHhm/u5CjLdtgX0EmTxokcHyvITPtD4YbKZgmROez4Ymow7pDCCwpBcOBcE3Kt+Tuoo6+O6jVsJYom95WFAfTEXrMsh5ziotnQHYl4ek9RC9/qEQiQboB5ARFJ9R3A=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      creationTimestamp: null
      name: ghcr-pull
      namespace: fuzequality
    type: kubernetes.io/dockerconfigjson
