---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull
  namespace: fuzequality
spec:
  encryptedData:
    .dockerconfigjson: AgAUgxQOin9/2DJm9qwMrao6dErSA9Cyaup8moV1b+1XvkhdJLYZhIXKH9C5P7PlEPMDJSZYVVy51khagLsiPD4iWfjpz3mCYINqjU7jbavxMxmFsfdCWucl1V/NwVxajW01BfSASUeMWCrbpg6WiuhfqhTc+j2tFxEUZyDrqYP7oDMgJNeYeZ03A1l7jKEAW5sEW/uKkQ/FrVVSSp9tYn1RicFyOZeW1Jx755mBk3h/0CzE9KaFAKLOSXiqH1LzsMi6VeIyTMd/FtHkVMSvBf0drVM22FHAIKbA9pbn+0hORPb6IGVQF+Gk7hcwOu25nPfKPOQL8/4jeK5LXFshI84DfRKaXflsbaOR5ngroQGF0LMSBAPzuTIHcmX0PY8oEwWRG4cAzfTaFaeFCeQYNbKqB2UmAjdE6bnxgrVwXEWgTbAVpAvZF6haimXVHJyKPqdLYMUSEmfpkM7YcRtNc9ygYqhBx1pppTZRa8pmsJE+c5mYAezEL23g+34DgoESZZNUqKVxBybBUYF5oWk8ePCT2h+eXQ3NJuF0OgJebOza9rSsjK9WtIDdnZ3izkC9m0nBpEdmOx/fSOWnIIA2qugz2mb53XtJNR8WGExmroqon5Bbg4fiV9CJS+Vy+vDwkYGbHLn7AinQwAKaZMc8Q9njy4HJZoMCnWMmkd6Qvzrge/cq99Y4ePOXnITUXjuNiQ/nM7rMtIuiCZhwIq4=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      creationTimestamp: null
      name: ghcr-pull
      namespace: fuzequality
    type: kubernetes.io/dockerconfigjson
