apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fuzequality-default
  labels:
    {{- include "fuzequality.labels" . | nindent 4 }}
spec:
  podSelector: { matchLabels: { app.kubernetes.io/name: fuzequality } }
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - { protocol: TCP, port: {{ .Values.backend.port }} }
        - { protocol: TCP, port: {{ .Values.frontend.port }} }
  egress:
    - to: [{ namespaceSelector: {} }]
    - to: [{ ipBlock: { cidr: 0.0.0.0/0 } }]
      ports:
        - { protocol: TCP, port: 443 }
        - { protocol: TCP, port: 53 }
        - { protocol: UDP, port: 53 }
