/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/custom-hostnames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the domains registered by the calling consumer
         * @description Scoped to the caller's route profile — a consumer never sees another
         *     consumer's domains.
         */
        get: operations["listCustomHostnames"];
        put?: never;
        /**
         * Begin validation + certificate issuance for a customer domain
         * @description Registers `domain` with Cloudflare for SaaS and materializes the routing
         *     Ingress. Returns immediately — issuance is asynchronous. The customer
         *     must publish the records in `verification` before the domain goes active.
         *
         *     Idempotent: re-posting a known domain returns the existing record (200).
         */
        post: operations["createCustomHostname"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/custom-hostnames/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The fully-qualified customer domain, e.g. `app.corpabc.com`. */
                domain: components["schemas"]["Domain"];
            };
            cookie?: never;
        };
        /**
         * Poll validation, certificate, and routing status
         * @description The endpoint a consumer UI polls. `verification` carries the records the
         *     customer still needs to publish; it stays populated after activation so
         *     the UI can show what was required, and is re-populated by Cloudflare
         *     ahead of each certificate renewal.
         *
         *     Suggested polling: every 10s for the first 2 minutes, then every 60s.
         *     Issuance typically completes 30s–5min after the records resolve.
         */
        get: operations["getCustomHostname"];
        put?: never;
        post?: never;
        /**
         * Deprovision a customer domain
         * @description Removes the Cloudflare custom hostname (revoking the edge certificate)
         *     and deletes the routing Ingress. Idempotent — unknown domains return 204.
         */
        delete: operations["deleteCustomHostname"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Verifies the configured backend (Cloudflare or stub) is reachable.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A fully-qualified domain the customer controls. Wildcards are rejected.
         *     Domains inside a FuzeInfra-managed zone (e.g. `*.fuzefront.com`) are
         *     rejected too — those are already served by the static wildcard and need
         *     no per-domain provisioning.
         * @example app.corpabc.com
         */
        Domain: string;
        CreateCustomHostnameRequest: {
            domain: components["schemas"]["Domain"];
            /**
             * @description Route profile to attach the domain to. Optional when the caller's
             *     token grants exactly one profile (the normal case). Supplying a
             *     profile the token does not grant is a 403.
             * @example fuzefront
             */
            profile?: string;
        };
        /** @description One DNS record the customer must publish. */
        VerificationRecord: {
            /**
             * @description `txt` for the ownership and DCV challenges, `cname` for the routing
             *     record that points the domain at the platform edge.
             * @enum {string}
             */
            method: "txt" | "cname";
            /**
             * @description The record NAME to create.
             * @example _cf-custom-hostname.app.corpabc.com
             */
            record: string;
            /**
             * @description The record VALUE.
             * @example 3b3a5f8c-1f3d-4d1f-9d63-9f0b2e1c4a77
             */
            value: string;
            /**
             * @description What the record proves. `ownership` proves domain control,
             *     `certificate` satisfies ACME DCV, `routing` sends traffic to us.
             * @enum {string}
             */
            purpose?: "ownership" | "certificate" | "routing";
        };
        /**
         * @description What the customer must publish. `method`/`record`/`value` mirror the
         *     PRIMARY (ownership) record for callers that only need one; `records`
         *     carries the complete set and is what a UI should render.
         */
        Verification: {
            /** @enum {string} */
            method: "txt" | "cname";
            record: string;
            value: string;
            records: components["schemas"]["VerificationRecord"][];
        };
        /**
         * @description Whether the customer's DNS points at us and ownership is proven.
         *     * `pending` — records not yet published/propagated
         *     * `active`  — ownership proven and the domain resolves to the platform
         *     * `moved`   — the domain stopped pointing at us
         *     * `blocked` — Cloudflare refused the hostname (already claimed elsewhere)
         *     * `error`   — validation failed; see `error`
         * @enum {string}
         */
        DnsStatus: "pending" | "active" | "moved" | "blocked" | "error";
        /**
         * @description Certificate lifecycle, suitable for direct display in a consumer UI.
         *     Everything before `active` is a normal in-progress state. `failed` and
         *     `expired` are terminal until the customer fixes their DNS; re-POST to
         *     retry.
         * @enum {string}
         */
        TlsStatus: "pending_validation" | "pending_issuance" | "pending_deployment" | "active" | "expired" | "failed";
        CustomHostname: {
            domain: components["schemas"]["Domain"];
            /** @description Route profile this domain is attached to. */
            profile: string;
            /**
             * @description True only when `dns_status=active` AND `tls_status=active` AND the
             *     routing Ingress exists. This is the single field a consumer needs to
             *     decide whether to advertise the domain to its user.
             */
            active: boolean;
            dns_status: components["schemas"]["DnsStatus"];
            tls_status: components["schemas"]["TlsStatus"];
            verification: components["schemas"]["Verification"];
            routing?: components["schemas"]["Routing"];
            certificate?: components["schemas"]["Certificate"];
            /** @description Human-readable reason when a status is `error`/`failed`. */
            error?: string | null;
            provider?: components["schemas"]["Provider"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string | null;
        };
        /** @description Where the customer should point DNS, and whether we can serve it. */
        Routing: {
            /**
             * @description The hostname the customer CNAMEs their domain to. Apex domains need
             *     a provider that supports CNAME flattening or ALIAS/ANAME records —
             *     see the consuming-repo guide.
             * @example connect.fuzefront.com
             */
            cname_target: string;
            /** @description Whether the in-cluster routing Ingress has been materialized. */
            ingress_ready: boolean;
            /** @description Name of the materialized Ingress (diagnostics only). */
            ingress_name?: string | null;
        };
        /** @description Present once Cloudflare has issued a certificate. */
        Certificate: {
            issuer?: string | null;
            /** Format: date-time */
            not_before?: string | null;
            /** Format: date-time */
            not_after?: string | null;
            serial_number?: string | null;
        };
        /**
         * @description Raw upstream detail, for debugging only. Consumers MUST NOT branch on
         *     these values — they are not part of the frozen contract.
         */
        Provider: {
            /** @enum {string} */
            name?: "cloudflare_for_saas" | "stub";
            /** @description Cloudflare custom hostname id. */
            id?: string | null;
            /** @description Raw Cloudflare hostname status. */
            status?: string | null;
            /** @description Raw Cloudflare `ssl.status`. */
            ssl_status?: string | null;
        } & {
            [key: string]: unknown;
        };
        CustomHostnameList: {
            items: components["schemas"]["CustomHostname"][];
            next_cursor?: string | null;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @enum {string} */
            provider?: "cloudflare_for_saas" | "stub";
            detail?: string | null;
        };
        Error: {
            /**
             * @description Stable machine-readable code.
             * @enum {string}
             */
            error: "bad_request" | "unauthorized" | "forbidden" | "not_found" | "validation_error" | "upstream_error" | "quota_exceeded";
            message: string;
            detail?: string | null;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Token does not grant the requested profile or domain. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such custom hostname for this consumer. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The domain was rejected (wildcard, managed zone, or malformed). */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Cloudflare or the Kubernetes API returned an error. */
        UpstreamError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCustomHostnames: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque cursor from a previous response's `next_cursor`. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of custom hostnames. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomHostnameList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["UpstreamError"];
        };
    };
    createCustomHostname: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomHostnameRequest"];
            };
        };
        responses: {
            /** @description Domain was already registered; existing record returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomHostname"];
                };
            };
            /** @description Domain accepted; validation and issuance started. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomHostname"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            502: components["responses"]["UpstreamError"];
        };
    };
    getCustomHostname: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The fully-qualified customer domain, e.g. `app.corpabc.com`. */
                domain: components["schemas"]["Domain"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current state of the custom hostname. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomHostname"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["UpstreamError"];
        };
    };
    deleteCustomHostname: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The fully-qualified customer domain, e.g. `app.corpabc.com`. */
                domain: components["schemas"]["Domain"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deprovisioned (or was not provisioned). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["UpstreamError"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Backend unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
