global:
  imagePullPolicy: Always
  imagePullSecrets:
    - name: ghcr-pull

backendImage:
  repository: ghcr.io/izzywdev/fuzequality-backend
  tag: 89b966f41a6e
frontendImage:
  repository: ghcr.io/izzywdev/fuzequality-frontend
  tag: 89b966f41a6e

ingress:
  enabled: true
  host: quality.fuzefront.com
