global:
  imagePullPolicy: Always
  imagePullSecrets:
    - name: ghcr-pull

backendImage:
  repository: ghcr.io/izzywdev/fuzequality-backend
  tag: 0be6f337c07c
frontendImage:
  repository: ghcr.io/izzywdev/fuzequality-frontend
  tag: 0be6f337c07c

ingress:
  enabled: true
  className: traefik
  host: quality.prod.fuzefront.com
