global:
  imagePullPolicy: Always
  imagePullSecrets:
    - name: ghcr-pull

backendImage:
  repository: ghcr.io/izzywdev/fuzequality-backend
  tag: d081b8f10842
frontendImage:
  repository: ghcr.io/izzywdev/fuzequality-frontend
  tag: d081b8f10842

ingress:
  enabled: true
  host: quality.fuzefront.com
