/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active plans
         * @description Public, cached list of active plans. No auth. Mirrors `createPlansRouter` -> `GET /plans`.
         */
        get: operations["getPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create or upgrade a subscription
         * @description Creates a Stripe subscription for the entity (creating the Stripe customer if needed) and mirrors it locally. Returns a `clientSecret` when Stripe needs SCA/3DS confirmation on the client. Mirrors `POST /subscriptions`.
         */
        post: operations["createSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{stripeSubscriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Stripe subscription id (e.g. `sub_...`). */
                stripeSubscriptionId: components["parameters"]["StripeSubscriptionId"];
            };
            cookie?: never;
        };
        /**
         * Get the local mirror of a subscription
         * @description Returns the locally-mirrored subscription by Stripe subscription id, or 404 if no mirror exists. Mirrors `GET /subscriptions/:id`.
         */
        get: operations["getSubscription"];
        put?: never;
        post?: never;
        /**
         * Cancel at period end (soft cancel)
         * @description Sets `cancel_at_period_end=true`; Stripe keeps the subscription active until the period boundary. Mirrors `DELETE /subscriptions/:id`.
         */
        delete: operations["cancelSubscription"];
        options?: never;
        head?: never;
        /**
         * Change plan or seat quantity
         * @description Upgrades prorate immediately (`create_prorations`); downgrades take effect at period end (`none`). Mirrors `PATCH /subscriptions/:id`.
         */
        patch: operations["updateSubscription"];
        trace?: never;
    };
    "/setup-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a SetupIntent to collect a payment method
         * @description Creates a Stripe SetupIntent (usage `off_session`) so the client can collect a payment method without an immediate charge (e.g. add a card during a no-card trial). Returns the `clientSecret` for the Stripe Payment Element. Mirrors `POST /setup-intent`.
         */
        post: operations["createSetupIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a one-time customer balance adjustment (admin only)
         * @description Adds a one-time customer balance adjustment (credit) via a Stripe customer balance transaction. A positive `amount` (in cents) credits the customer (reduces what they owe). Mirrors `POST /credits`.
         */
        post: operations["addCredits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe webhook receiver
         * @description Receives Stripe events. The body MUST be the raw signed bytes (`application/json` consumed via `express.raw`) so signature verification works. Public (no internal token) — authenticity is established by the `Stripe-Signature` header. Idempotent: duplicate deliveries of the same event id return 200 without re-processing. Mirrors `POST /webhooks/stripe`.
         */
        post: operations["receiveStripeWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness / readiness probe
         * @description Always available, even in degraded mode (no DB / no Stripe key). NOTE: mounted at the service root (`/health`), NOT under `/api/v1/billing` -- call it on the bare server origin.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Which platform entity owns the billing relationship.
         * @enum {string}
         */
        EntityType: "user" | "organization";
        /**
         * @description Plan tier name resolved from the Stripe price (free / starter / pro / enterprise, or any custom tier). Open string by design.
         * @example free
         * @example starter
         * @example pro
         * @example enterprise
         */
        PlanTier: string;
        /**
         * @description Mirrors Stripe subscription status values. Open string by design.
         * @example trialing
         * @example active
         * @example past_due
         * @example canceled
         * @example unpaid
         * @example incomplete
         * @example incomplete_expired
         */
        SubscriptionStatus: string;
        EntityRef: {
            entityType: components["schemas"]["EntityType"];
            /**
             * Format: uuid
             * @description The id of the user or organization.
             */
            entityId: string;
        };
        BillingSubscription: {
            /**
             * Format: uuid
             * @description Local billing.subscriptions primary key.
             */
            id: string;
            /**
             * Format: uuid
             * @description Local billing.customers primary key.
             */
            customerId: string;
            stripeSubscriptionId: string;
            stripePriceId: string;
            planTier: components["schemas"]["PlanTier"];
            status: components["schemas"]["SubscriptionStatus"];
            seatQuantity: number;
            /** Format: date-time */
            trialStart: string | null;
            /** Format: date-time */
            trialEnd: string | null;
            /** Format: date-time */
            currentPeriodStart: string | null;
            /** Format: date-time */
            currentPeriodEnd: string | null;
            cancelAtPeriodEnd: boolean;
            /** Format: date-time */
            canceledAt: string | null;
        };
        Plan: {
            stripePriceId: string;
            stripeProductId: string;
            tierName: components["schemas"]["PlanTier"];
            displayName: string;
            /**
             * @description Billing cadence (`month` / `year`, or any Stripe interval).
             * @example month
             * @example year
             */
            billingInterval: string;
            /** @description Unit amount in the currency's minor unit (cents). */
            unitAmount: number;
            /**
             * @description ISO 4217 currency code.
             * @example usd
             */
            currency: string;
            seatBased: boolean;
            meteredMeterName: string | null;
            features: string[];
            isActive: boolean;
            sortOrder: number;
        };
        CreateSubscriptionRequest: {
            entityType: components["schemas"]["EntityType"];
            /** Format: uuid */
            entityId: string;
            priceId: string;
            /** @description Start a no-card trial (Stripe trial_period_days). */
            trial?: boolean;
            trialPeriodDays?: number;
            /** @description Seat quantity for per-seat plans. Defaults to 1. */
            seatQuantity?: number;
            /** @description Existing Stripe PaymentMethod to attach (omit for no-card trials). */
            paymentMethodId?: string;
        };
        CreateSubscriptionResponse: {
            subscription: components["schemas"]["BillingSubscription"];
            /** @description Set when Stripe needs SCA/3DS confirmation on the client. */
            clientSecret?: string;
            /** @description True when the client must confirm a PaymentIntent/SetupIntent. */
            requiresAction: boolean;
        };
        UpdateSubscriptionRequest: {
            /** @description New price (plan change). */
            priceId?: string;
            /** @description New seat quantity. */
            seatQuantity?: number;
        };
        AddCreditsRequest: {
            entityType: components["schemas"]["EntityType"];
            /** Format: uuid */
            entityId: string;
            /** @description Amount in cents; a positive value credits the customer. */
            amount: number;
            note?: string;
        };
        Error: {
            error: string;
        };
        StripeErrorBody: {
            /** @example stripe error */
            error: string;
            message?: string;
        };
        ValidationErrorBody: {
            /** @example invalid request */
            error: string;
            /** @description Zod flatten() output describing the field errors. */
            details?: unknown;
        };
    };
    responses: {
        /** @description Missing or invalid internal token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request body failed validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorBody"];
            };
        };
        /** @description Upstream Stripe error (bad gateway). */
        StripeError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["StripeErrorBody"];
            };
        };
        /** @description Unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description The Stripe subscription id (e.g. `sub_...`). */
        StripeSubscriptionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active plan catalogue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plans: components["schemas"]["Plan"][];
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Subscription created (may require client-side action). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSubscriptionResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["StripeError"];
        };
    };
    getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Stripe subscription id (e.g. `sub_...`). */
                stripeSubscriptionId: components["parameters"]["StripeSubscriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The locally-mirrored subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subscription: components["schemas"]["BillingSubscription"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Stripe subscription id (e.g. `sub_...`). */
                stripeSubscriptionId: components["parameters"]["StripeSubscriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The subscription mirror with cancellation scheduled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subscription: components["schemas"]["BillingSubscription"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["StripeError"];
        };
    };
    updateSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The Stripe subscription id (e.g. `sub_...`). */
                stripeSubscriptionId: components["parameters"]["StripeSubscriptionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description The updated subscription mirror. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subscription: components["schemas"]["BillingSubscription"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["StripeError"];
        };
    };
    createSetupIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityRef"];
            };
        };
        responses: {
            /** @description SetupIntent created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Stripe SetupIntent client secret for the Payment Element. */
                        clientSecret: string;
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["StripeError"];
        };
    };
    addCredits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCreditsRequest"];
            };
        };
        responses: {
            /** @description Balance transaction created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Stripe customer balance transaction id. */
                        id: string;
                        /** @description Resulting customer balance in cents (negative = credit). */
                        endingBalance: number;
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["StripeError"];
        };
    };
    receiveStripeWebhook: {
        parameters: {
            query?: never;
            header: {
                /** @description Stripe webhook signature header used to verify the payload. */
                "Stripe-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Event received (and processed, unless a duplicate). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        received: boolean;
                        /** @description True when the event id was already processed. */
                        duplicate?: boolean;
                    };
                };
            };
            /** @description Missing/invalid signature header or payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                        /** @example billing-service */
                        service: string;
                    };
                };
            };
        };
    };
}
