/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active plans
         * @description Public, cached list of active plans. No auth. Mirrors `createPlansRouter` -> `GET /plans`.
         */
        get: operations["getPlans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create or upgrade a subscription
         * @description Creates a provider subscription for the entity (creating the provider customer if needed) and mirrors it locally. Returns a `clientSecret` when the provider needs SCA/3DS confirmation on the client. Mirrors `POST /subscriptions`.
         */
        post: operations["createSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{subscriptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The provider subscription id (e.g. `sub_...`). */
                subscriptionId: components["parameters"]["SubscriptionId"];
            };
            cookie?: never;
        };
        /**
         * Get the local mirror of a subscription
         * @description Returns the locally-mirrored subscription by provider subscription id, or 404 if no mirror exists. Mirrors `GET /subscriptions/:id`.
         */
        get: operations["getSubscription"];
        put?: never;
        post?: never;
        /**
         * Cancel at period end (soft cancel)
         * @description Sets `cancel_at_period_end=true`; the provider keeps the subscription active until the period boundary. Mirrors `DELETE /subscriptions/:id`.
         */
        delete: operations["cancelSubscription"];
        options?: never;
        head?: never;
        /**
         * Change plan or seat quantity
         * @description Upgrades prorate immediately (`create_prorations`); downgrades take effect at period end (`none`). Mirrors `PATCH /subscriptions/:id`.
         */
        patch: operations["updateSubscription"];
        trace?: never;
    };
    "/setup-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a SetupIntent to collect a payment method
         * @description Creates a provider SetupIntent (usage `off_session`) so the client can collect a payment method without an immediate charge (e.g. add a card during a no-card trial). Returns the `clientSecret` for the provider Payment Element. Mirrors `POST /setup-intent`.
         */
        post: operations["createSetupIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a hosted Checkout Session (subscription mode)
         * @description Creates a hosted Checkout Session in `subscription` mode for the given organization and plan, and returns the provider-hosted `url` to redirect the customer to. the provider collects the card on its hosted page; on completion the provider fires `checkout.session.completed`, which activates the local subscription mirror. We use HOSTED Checkout (not in-app Elements) so no raw card data touches our surface. Mirrors `POST /checkout`.
         *
         *     Authorization (money path): the host proxy authenticates the platform JWT, authorizes the caller against the target organization, and forwards the SERVER-DERIVED actor + entity as trusted headers (`X-Billing-Actor-User-Id`, `X-Billing-Entity-Type`, `X-Billing-Entity-Id`; short aliases `X-FF-Actor-Id` / `X-FF-Org-Id`). The service RE-VERIFIES that `organizationId` matches the authorized entity before creating any provider object (rejects with 403 otherwise), and validates `planId` against the active plan catalogue (rejects unknown/inactive plans with 400). `planId: "basic"` resolves to the live $9/mo price.
         */
        post: operations["createCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a hosted Checkout Session (one-time payment mode)
         * @description Creates a hosted Checkout Session in `payment` mode for an allowlisted consumer product (e.g. `mendys-datasets`) and returns the provider-hosted `url` to redirect the buyer to. The caller supplies the priced line items (name + unit amount in cents + quantity); the service builds provider `price_data` from them — no provider price catalogue entry is required. On completion the provider fires `checkout.session.completed` (mode `payment`), which upserts the local `billing.payments` mirror and emits `billing.payment.completed` on Kafka. Failure/expiry are mirrored via `payment_intent.payment_failed` / `checkout.session.expired`. Mirrors `POST /payments/checkout`.
         *
         *     Authorization (money path): identical to `/checkout` — the host proxy authenticates the platform JWT, authorizes the caller against the target entity, and forwards the SERVER-DERIVED actor + entity as trusted headers (`X-Billing-Actor-User-Id`, `X-Billing-Entity-Type`, `X-Billing-Entity-Id`; aliases `X-FF-Actor-Id` / `X-FF-Org-Id`). The service RE-VERIFIES that the body's `entityType`/`entityId` match the authorized entity before creating any provider object (mismatch → 403). `productKey` must be in the server-side allowlist (`BILLING_PRODUCT_KEYS`), `currency` in the configured allowlist (default `usd`, `eur`), and each line amount plus the order total are bounded server-side (`BILLING_PAYMENT_MAX_TOTAL_CENTS`, default 5,000,000 cents) — violations → 400.
         *
         *     Idempotency: retries with IDENTICAL parameters dedupe to one provider session (param-fingerprint idempotency key, same scheme as `/checkout`); any changed parameter yields a fresh session.
         */
        post: operations["createPaymentCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The hosted Checkout Session id (`cs_...`). */
                sessionId: string;
            };
            cookie?: never;
        };
        /**
         * Get the local payment mirror for a Checkout Session
         * @description Returns the `billing.payments` mirror row for a payment-mode Checkout Session — the reconciliation-polling surface for consumer services that missed (or cannot receive) the `billing.payment.completed` event. `status` is `pending` until a webhook lands, then `paid` / `failed` / `expired`. 404 when the session is unknown. When the local row is missing but the session exists at the provider AND its `productKey` metadata is allowlisted, the service falls back to the live provider, re-mirrors the row, and returns it (singleton resource — pagination exempt).
         *
         *     Authorization: same model as `/payments/checkout`; the proxy-authorized entity must OWN the session (mismatch → 403).
         */
        get: operations["getPaymentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a one-time customer balance adjustment (admin only)
         * @description Adds a one-time customer balance adjustment (credit) via a provider customer balance transaction. A positive `amount` (in cents, bounded) credits the customer (reduces what they owe). Mirrors `POST /credits`.
         *
         *     ADMIN-ONLY: in addition to the internal token, the host proxy must supply `X-Billing-Actor-Is-Admin: true` (it sets this only for callers it has authorized as platform admins). Without it the service responds 403. `amount` must be a positive integer and is capped server-side.
         */
        post: operations["addCredits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the authorized entity's invoices
         * @description Returns the invoice history for the proxy-authorized entity (user or organization), most-recent first. Served from the local invoice store, synced from the payment provider. Read-only.
         *
         *     Authorization: behind the internal-token guard; the entity is the SERVER-DERIVED actor context the proxy injects (`X-Billing-Actor-User-Id`, `X-Billing-Entity-Type`, `X-Billing-Entity-Id`; short aliases `X-FF-Actor-Id` / `X-FF-Org-Id`). Identity is never taken from the query string. An entity that has never had billing returns `{ invoices: [], nextCursor: null }` (200, not an error).
         *
         *     Pagination is opaque-cursor based: pass the previous response's `nextCursor` as `cursor` to fetch the next page. `nextCursor` is null on the last page.
         */
        get: operations["listInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force a provider→store resync of the authorized entity's invoices
         * @description Forces a resync of the proxy-authorized entity's invoices from the payment provider into the local invoice store, then returns the number of invoices upserted. Idempotent — safe to call repeatedly.
         *
         *     Authorization is identical to `GET /invoices`: behind the internal-token guard, with the entity taken from the SERVER-DERIVED actor context the proxy injects (`X-Billing-Actor-User-Id`, `X-Billing-Entity-Type`, `X-Billing-Entity-Id`). An entity that has never had billing returns `{ synced: 0 }` (200, not an error).
         */
        post: operations["syncInvoices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Customer Portal session
         * @description Creates a Customer Portal session for the proxy-authorized entity and returns the provider-hosted `url` to redirect the customer to, where they can manage their subscription and payment methods. Mirrors `POST /portal`.
         *
         *     Authorization: behind the internal-token guard; the entity is the SERVER-DERIVED actor context the proxy injects (the entity is NEVER taken from the request body). An entity that has never had a billing customer cannot open a portal -> 409.
         */
        post: operations["createPortalSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provider webhook receiver
         * @description Provider webhook receiver; authenticity verified by the provider signature. Receives events from the configured payment provider (selected by the `provider` path slug). The body MUST be the raw signed bytes (`application/json` consumed via `express.raw`) so signature verification works. Public (no internal token) — authenticity is established by the provider signature header. Idempotent: duplicate deliveries of the same event id return 200 without re-processing.
         */
        post: operations["receiveProviderWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness / readiness probe
         * @description Always available, even in degraded mode (no DB / no provider key). NOTE: mounted at the service root (`/health`), NOT under `/api/v1/billing` -- call it on the bare server origin.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Which platform entity owns the billing relationship.
         * @enum {string}
         */
        EntityType: "user" | "organization";
        /**
         * @description Plan tier name resolved from the provider price (free / starter / pro / enterprise, or any custom tier). Open string by design.
         * @example free
         * @example starter
         * @example pro
         * @example enterprise
         */
        PlanTier: string;
        /**
         * @description Mirrors provider subscription status values. Open string by design.
         * @example trialing
         * @example active
         * @example past_due
         * @example canceled
         * @example unpaid
         * @example incomplete
         * @example incomplete_expired
         */
        SubscriptionStatus: string;
        EntityRef: {
            entityType: components["schemas"]["EntityType"];
            /**
             * Format: uuid
             * @description The id of the user or organization.
             */
            entityId: string;
        };
        BillingSubscription: {
            /**
             * Format: uuid
             * @description Local billing.subscriptions primary key.
             */
            id: string;
            /**
             * Format: uuid
             * @description Local billing.customers primary key.
             */
            customerId: string;
            subscriptionId: string;
            priceId: string;
            planTier: components["schemas"]["PlanTier"];
            status: components["schemas"]["SubscriptionStatus"];
            seatQuantity: number;
            /** Format: date-time */
            trialStart: string | null;
            /** Format: date-time */
            trialEnd: string | null;
            /** Format: date-time */
            currentPeriodStart: string | null;
            /** Format: date-time */
            currentPeriodEnd: string | null;
            cancelAtPeriodEnd: boolean;
            /** Format: date-time */
            canceledAt: string | null;
        };
        Plan: {
            priceId: string;
            productId: string;
            tierName: components["schemas"]["PlanTier"];
            displayName: string;
            /**
             * @description Billing cadence (`month` / `year`, or any provider interval).
             * @example month
             * @example year
             */
            billingInterval: string;
            /** @description Unit amount in the currency's minor unit (cents). */
            unitAmount: number;
            /**
             * @description ISO 4217 currency code.
             * @example usd
             */
            currency: string;
            seatBased: boolean;
            meteredMeterName: string | null;
            features: string[];
            isActive: boolean;
            sortOrder: number;
        };
        CreateSubscriptionRequest: {
            entityType: components["schemas"]["EntityType"];
            /** Format: uuid */
            entityId: string;
            priceId: string;
            /** @description Start a no-card trial (provider trial_period_days). */
            trial?: boolean;
            trialPeriodDays?: number;
            /** @description Seat quantity for per-seat plans. Defaults to 1. */
            seatQuantity?: number;
            /** @description Existing provider payment method to attach (omit for no-card trials). */
            paymentMethodId?: string;
        };
        CreateSubscriptionResponse: {
            subscription: components["schemas"]["BillingSubscription"];
            /** @description Set when the provider needs SCA/3DS confirmation on the client. */
            clientSecret?: string;
            /** @description True when the client must confirm a PaymentIntent/SetupIntent. */
            requiresAction: boolean;
        };
        UpdateSubscriptionRequest: {
            /** @description New price (plan change). */
            priceId?: string;
            /** @description New seat quantity. */
            seatQuantity?: number;
        };
        AddCreditsRequest: {
            entityType: components["schemas"]["EntityType"];
            /** Format: uuid */
            entityId: string;
            /** @description Amount in cents; a positive value credits the customer. Bounded server-side (1..10_000_000 cents) — MEDIUM-1. */
            amount: number;
            note?: string;
        };
        CheckoutSessionRequest: {
            /** @description Logical plan id (e.g. `basic`), a tier name, or a provider price id present in the active catalogue. Validated against active plans; `basic` resolves to the live $9/mo price. */
            planId: string;
            /**
             * Format: uuid
             * @description Target organization. MUST match the proxy-authorized entity (re-verified server-side; mismatch → 403).
             */
            organizationId: string;
            /**
             * Format: uri
             * @description Where the provider redirects after a completed checkout.
             */
            successUrl: string;
            /**
             * Format: uri
             * @description Where the provider redirects if the customer cancels.
             */
            cancelUrl: string;
        };
        CheckoutSessionResponse: {
            /** @description provider-hosted Checkout URL to redirect the customer to. */
            url: string | null;
            /** @description The hosted Checkout Session id (`cs_...`). */
            sessionId: string;
        };
        /**
         * @description Lifecycle of a payment-mode Checkout Session mirror: `pending` from session creation until a webhook lands; then `paid` (checkout.session.completed, paid), `failed` (payment_intent.payment_failed) or `expired` (checkout.session.expired). `paid` is terminal and never downgraded.
         * @enum {string}
         */
        PaymentStatus: "pending" | "paid" | "failed" | "expired";
        PaymentLineItem: {
            /** @description Line-item display name shown on the provider-hosted page. */
            name: string;
            /** @description Optional line-item description shown under the name. */
            description?: string;
            /** @description Unit price in the currency's minor unit (cents). Bounded server-side together with the order total (`BILLING_PAYMENT_MAX_TOTAL_CENTS`). */
            unitAmountCents: number;
            /** @description Units of this line item. */
            quantity: number;
        };
        PaymentCheckoutRequest: {
            /** @description Consumer product key (e.g. `mendys-datasets`). MUST be in the server-side allowlist (`BILLING_PRODUCT_KEYS`); unknown keys → 400. */
            productKey: string;
            /** @description The consumer product's own order id. Stamped on the session as `client_reference_id` + metadata and echoed on `billing.payment.completed` so the product can correlate. */
            externalOrderId: string;
            entityType: components["schemas"]["EntityType"];
            /**
             * Format: uuid
             * @description Paying entity. MUST match the proxy-authorized entity (re-verified server-side; mismatch → 403).
             */
            entityId: string;
            /**
             * @description ISO 4217 currency code (case-insensitive; lowercased server-side). Must be in the configured allowlist (default `usd`, `eur`).
             * @example usd
             * @example eur
             */
            currency: string;
            lineItems: components["schemas"]["PaymentLineItem"][];
            /**
             * Format: uri
             * @description Where the provider redirects after a completed payment.
             */
            successUrl: string;
            /**
             * Format: uri
             * @description Where the provider redirects if the buyer cancels.
             */
            cancelUrl: string;
        };
        PaymentCheckoutResponse: {
            /** @description The hosted Checkout Session id (`cs_...`). */
            sessionId: string;
            /** @description provider-hosted Checkout URL to redirect the buyer to. */
            url: string | null;
        };
        BillingPayment: {
            /**
             * Format: uuid
             * @description Local billing.payments primary key.
             */
            id: string;
            /** @description hosted Checkout Session id (`cs_...`). */
            sessionId: string;
            /** @description provider PaymentIntent id (`pi_...`); null until the provider creates the intent (typically when the buyer reaches the payment page). */
            paymentIntentId: string | null;
            productKey: string;
            externalOrderId: string;
            entityType: components["schemas"]["EntityType"];
            /** Format: uuid */
            entityId: string;
            /** @description Order total in the currency's minor unit (cents). */
            amountTotalCents: number;
            /**
             * @description ISO 4217 currency code, lowercased.
             * @example usd
             */
            currency: string;
            status: components["schemas"]["PaymentStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BillingInvoice: {
            /**
             * Format: uuid
             * @description FuzeFront invoice id (opaque, stable). A FuzeFront UUID, not a provider id.
             */
            id: string;
            /** @description Human-facing invoice number; null for drafts without one. */
            number: string | null;
            /**
             * Format: date-time
             * @description ISO-8601 issue timestamp.
             */
            created: string;
            /** @description Amount due in the currency's minor unit (cents). */
            amountDue: number;
            /** @description Amount paid in the currency's minor unit (cents). */
            amountPaid: number;
            /**
             * @description ISO 4217 currency code, lowercased.
             * @example usd
             */
            currency: string;
            /**
             * @description Neutral invoice status: draft|open|paid|void|uncollectible.
             * @example draft
             * @example open
             * @example paid
             * @example void
             * @example uncollectible
             */
            status: string;
            /** @description Provider-hosted document URL, opaque to consumers; null when unavailable. */
            hostedInvoiceUrl: string | null;
            /** @description Provider-hosted document URL, opaque to consumers; null when unavailable. */
            invoicePdf: string | null;
        };
        InvoiceListResponse: {
            invoices: components["schemas"]["BillingInvoice"][];
            /** @description Opaque cursor for the next page; null on the last page. */
            nextCursor: string | null;
        };
        PortalSessionRequest: {
            /**
             * Format: uri
             * @description Where the provider returns the customer after they leave the portal.
             */
            returnUrl: string;
        };
        PortalSessionResponse: {
            /** @description provider-hosted Customer Portal url to redirect the customer to. */
            url: string;
        };
        Error: {
            error: string;
        };
        ProviderErrorBody: {
            /** @example provider error */
            error: string;
            message?: string;
        };
        ValidationErrorBody: {
            /** @example invalid request */
            error: string;
            /** @description Zod flatten() output describing the field errors. */
            details?: unknown;
        };
    };
    responses: {
        /** @description Missing or invalid internal token, or missing actor context. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The authenticated/authorized caller may not act on the target object (e.g. organizationId does not match the authorized entity, or the operation requires platform-admin context). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request body failed validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorBody"];
            };
        };
        /** @description Upstream provider error (bad gateway). */
        ProviderError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProviderErrorBody"];
            };
        };
        /** @description Unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description The provider subscription id (e.g. `sub_...`). */
        SubscriptionId: string;
        /** @description Authenticated actor (the platform user id) — set by the host proxy AFTER it authenticates + authorizes the caller. Short alias: `X-FF-Actor-Id`. */
        ActorUserIdHeader: string;
        /** @description Server-derived authorized entity type (`user`|`organization`) set by the proxy. When the `X-FF-Org-Id` alias is used this is implied to be `organization`. */
        EntityTypeHeader: components["schemas"]["EntityType"];
        /** @description Server-derived authorized entity id set by the proxy. The service re-verifies the request target matches this. Short alias: `X-FF-Org-Id`. */
        EntityIdHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPlans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active plan catalogue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plans: components["schemas"]["Plan"][];
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Subscription created (may require client-side action). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSubscriptionResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["ProviderError"];
        };
    };
    getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The provider subscription id (e.g. `sub_...`). */
                subscriptionId: components["parameters"]["SubscriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The locally-mirrored subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subscription: components["schemas"]["BillingSubscription"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The provider subscription id (e.g. `sub_...`). */
                subscriptionId: components["parameters"]["SubscriptionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The subscription mirror with cancellation scheduled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subscription: components["schemas"]["BillingSubscription"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["ProviderError"];
        };
    };
    updateSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The provider subscription id (e.g. `sub_...`). */
                subscriptionId: components["parameters"]["SubscriptionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description The updated subscription mirror. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subscription: components["schemas"]["BillingSubscription"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["ProviderError"];
        };
    };
    createSetupIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityRef"];
            };
        };
        responses: {
            /** @description SetupIntent created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description provider SetupIntent client secret for the Payment Element. */
                        clientSecret: string;
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["ProviderError"];
        };
    };
    createCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated actor (the platform user id) — set by the host proxy AFTER it authenticates + authorizes the caller. Short alias: `X-FF-Actor-Id`. */
                "X-Billing-Actor-User-Id": components["parameters"]["ActorUserIdHeader"];
                /** @description Server-derived authorized entity type (`user`|`organization`) set by the proxy. When the `X-FF-Org-Id` alias is used this is implied to be `organization`. */
                "X-Billing-Entity-Type": components["parameters"]["EntityTypeHeader"];
                /** @description Server-derived authorized entity id set by the proxy. The service re-verifies the request target matches this. Short alias: `X-FF-Org-Id`. */
                "X-Billing-Entity-Id": components["parameters"]["EntityIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSessionRequest"];
            };
        };
        responses: {
            /** @description Checkout Session created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSessionResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["ProviderError"];
        };
    };
    createPaymentCheckoutSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated actor (the platform user id) — set by the host proxy AFTER it authenticates + authorizes the caller. Short alias: `X-FF-Actor-Id`. */
                "X-Billing-Actor-User-Id": components["parameters"]["ActorUserIdHeader"];
                /** @description Server-derived authorized entity type (`user`|`organization`) set by the proxy. When the `X-FF-Org-Id` alias is used this is implied to be `organization`. */
                "X-Billing-Entity-Type": components["parameters"]["EntityTypeHeader"];
                /** @description Server-derived authorized entity id set by the proxy. The service re-verifies the request target matches this. Short alias: `X-FF-Org-Id`. */
                "X-Billing-Entity-Id": components["parameters"]["EntityIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCheckoutRequest"];
            };
        };
        responses: {
            /** @description Payment-mode Checkout Session created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentCheckoutResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Idempotency-key conflict (same key, different params). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderErrorBody"];
                };
            };
            502: components["responses"]["ProviderError"];
        };
    };
    getPaymentSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated actor (the platform user id) — set by the host proxy AFTER it authenticates + authorizes the caller. Short alias: `X-FF-Actor-Id`. */
                "X-Billing-Actor-User-Id": components["parameters"]["ActorUserIdHeader"];
                /** @description Server-derived authorized entity type (`user`|`organization`) set by the proxy. When the `X-FF-Org-Id` alias is used this is implied to be `organization`. */
                "X-Billing-Entity-Type": components["parameters"]["EntityTypeHeader"];
                /** @description Server-derived authorized entity id set by the proxy. The service re-verifies the request target matches this. Short alias: `X-FF-Org-Id`. */
                "X-Billing-Entity-Id": components["parameters"]["EntityIdHeader"];
            };
            path: {
                /** @description The hosted Checkout Session id (`cs_...`). */
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The payment mirror row. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payment: components["schemas"]["BillingPayment"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["ProviderError"];
        };
    };
    addCredits: {
        parameters: {
            query?: never;
            header: {
                /** @description Set to `true` by the proxy ONLY for platform-admin-authorized callers. Required — absent/other values are rejected with 403. */
                "X-Billing-Actor-Is-Admin": "true";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCreditsRequest"];
            };
        };
        responses: {
            /** @description Balance transaction created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description payment-provider customer balance transaction id. */
                        id: string;
                        /** @description Resulting customer balance in cents (negative = credit). */
                        endingBalance: number;
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["ProviderError"];
        };
    };
    listInvoices: {
        parameters: {
            query?: {
                /** @description Page size, clamped server-side to 1..100. Defaults to 20. */
                limit?: number;
                /** @description Opaque cursor (previous `nextCursor`). Use the previous response's `nextCursor` to fetch the next page. */
                cursor?: string;
            };
            header: {
                /** @description Authenticated actor (the platform user id) — set by the host proxy AFTER it authenticates + authorizes the caller. Short alias: `X-FF-Actor-Id`. */
                "X-Billing-Actor-User-Id": components["parameters"]["ActorUserIdHeader"];
                /** @description Server-derived authorized entity type (`user`|`organization`) set by the proxy. When the `X-FF-Org-Id` alias is used this is implied to be `organization`. */
                "X-Billing-Entity-Type": components["parameters"]["EntityTypeHeader"];
                /** @description Server-derived authorized entity id set by the proxy. The service re-verifies the request target matches this. Short alias: `X-FF-Org-Id`. */
                "X-Billing-Entity-Id": components["parameters"]["EntityIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of invoices for the entity (possibly empty). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceListResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["ProviderError"];
        };
    };
    syncInvoices: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated actor (the platform user id) — set by the host proxy AFTER it authenticates + authorizes the caller. Short alias: `X-FF-Actor-Id`. */
                "X-Billing-Actor-User-Id": components["parameters"]["ActorUserIdHeader"];
                /** @description Server-derived authorized entity type (`user`|`organization`) set by the proxy. When the `X-FF-Org-Id` alias is used this is implied to be `organization`. */
                "X-Billing-Entity-Type": components["parameters"]["EntityTypeHeader"];
                /** @description Server-derived authorized entity id set by the proxy. The service re-verifies the request target matches this. Short alias: `X-FF-Org-Id`. */
                "X-Billing-Entity-Id": components["parameters"]["EntityIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resync completed; reports how many invoices were upserted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Number of invoices upserted into the local store. */
                        synced: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["ProviderError"];
        };
    };
    createPortalSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Authenticated actor (the platform user id) — set by the host proxy AFTER it authenticates + authorizes the caller. Short alias: `X-FF-Actor-Id`. */
                "X-Billing-Actor-User-Id": components["parameters"]["ActorUserIdHeader"];
                /** @description Server-derived authorized entity type (`user`|`organization`) set by the proxy. When the `X-FF-Org-Id` alias is used this is implied to be `organization`. */
                "X-Billing-Entity-Type": components["parameters"]["EntityTypeHeader"];
                /** @description Server-derived authorized entity id set by the proxy. The service re-verifies the request target matches this. Short alias: `X-FF-Org-Id`. */
                "X-Billing-Entity-Id": components["parameters"]["EntityIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalSessionRequest"];
            };
        };
        responses: {
            /** @description Portal session created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalSessionResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            /** @description The entity has no billing customer to manage. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example no billing customer */
                        error: string;
                        message?: string;
                    };
                };
            };
            502: components["responses"]["ProviderError"];
        };
    };
    receiveProviderWebhook: {
        parameters: {
            query?: never;
            header: {
                /** @description Provider webhook signature header used to verify the payload authenticity. */
                "X-Provider-Signature": string;
            };
            path: {
                /** @description Payment-provider slug identifying which provider sent the webhook (e.g. the configured payment provider). Selects the signature verifier + event decoder. */
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Event received (and processed, unless a duplicate). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        received: boolean;
                        /** @description True when the event id was already processed. */
                        duplicate?: boolean;
                    };
                };
            };
            /** @description Missing/invalid signature header or payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                        /** @example billing-service */
                        service: string;
                    };
                };
            };
        };
    };
}
