apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fuzeservice
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/izzywdev/FuzeService.git
    targetRevision: main
    path: helm/fuzeservice
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fuzeservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
