apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fuzecontact
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/izzywdev/FuzeContact.git
    targetRevision: main
    path: helm/fuzecontact
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fuzecontact
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
