---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  creationTimestamp: null
  name: a2a-card-signing
  namespace: fuzefront
spec:
  encryptedData:
    jws.key: AgBVG8m6kXmyF7vdT2UkJvbT3OceBJPbJb3bFdOMmwO19CkGTT2KTTUClqvfFrRiqNIHsS6dzjk/xor0Sa7ydpNRs5EUjfFsiMATSxIlGPePjSEK7glz5B6KI6Mw+w3Yh0Fcq8GLEBPP5FucUQBdo7pZMzyLs7Oh33plmUh9WU0v79ybszhp70Vje7+z8usxE7bEzCic9fpaPzNXS/fIUptlU6cNHfa7o08jFizqOvxgtxj8nAkTgrDYAU78xWq4o8XlNynUFkK5u2Im8w/jRuP5gPAZ4FErn92Xl5BR/dX86XTFP7+COghbtS1mnDVf2O20wHKHu5BbliAU/H/wZoBaW2Z8tfy1ORuZTcce1fkVHA8NenqhbES1b5euS26PbJCDpWGF+cYcZZ71ct3+4t4qRmRo8ee5B02oDT/dvEOtk/uMpxCGzyM8dhJwmCRSkPxq7kVgKSeVt2tXZtDhBArSIZxPFX2NImnETn22XeeSbn879Bfc+Y0mHLJBkprZy1K0Rsf6G9mvYX3k77Q6XOa9pBky2x7Kk3rB6SDQcsra5fI04QVhw80jMspW7Q3mmu2a4SjsxLgbFZf0CnQKVu/hC9FpGvI26xnzhuc3dS9leAfuWhWYk3eWAgPXKNWtNa/cBWpZAe3z3NMyDlsVxEz780aV4MDJxp7ynlYkqCNhiHUmTc9WSPMBgLM1nOxw9FZwafcXvgi5H5gSfgRLXbxsGo9oK9yHs4YO1NQ8FRhUHjef/3dCIEpAUIeHkGv4jWRCRWvlQBznPx11ik8MSYUp
  template:
    metadata:
      creationTimestamp: null
      name: a2a-card-signing
      namespace: fuzefront
