---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: selection-list-secrets
  namespace: fuzefront
spec:
  encryptedData:
    DB_PASSWORD: AgDABvjwiNPFbx+zCykSwJZOrD24kwwYReaeo5KLsggjkB+spxVyPdklyfhUwl5aV52XWHZ7LuowKRS3dO7dVPqRWEO4gpGBTRObj8EWYyf4gTXuGT86dRiUsstpfDVZksMfPWm90lVxQ2/Gt44q8R4aImckHJ7UF4g81VSyNwj+FTkTtuguIHiqDZMzDkvNQdgYnGO3SO1ChpKb77gd5sQZiAKNTgJ1S5me5ZHeg1k/YDhAklznAh1quYOepoc6fEKJRcIN5wnyq/I0C5E66cxbhKinjWw9YUR82wxCjxGqo0YAFjBd0cAWrJ328deSJ8AN1sRtAmKBBKIwOdJRNeO3eGsX2hG5yPs/3UIH8PMPWYNBQ5FJmy7Z0UF7lK/mN2eI61ooDDY4haWO+1U2kNEF/wC03uzLlz3kPgBZ/TfTWEiv/gW9Z+CjAQFSll5uX2Epi9PN3pYsVMuRsE7NGRWEiiDwNrd4fX9cRXbfQwY7svTnw3NwuU0P6hIGc//a+9fp/QmsJnf5/ueV5xySh+p1K4hQT7hgiim7zH7cK4wnm5/MLYn6ZU4jF07H+8Li/ImVofpA1SZ76Rcc2mEyByYflxaHa0554RKzdMdoCqABgPADeaTGecPz6ZzGbuaZlbtYgxtRVC5dYYvU/VcDzNRvY0noi588/7AoXLoEUMNw4JUjf1LAfVmoZX/tWX1JsCIplSyVB3yRTPph1LFABsl89KENl1BAPNjjWxi44qqS6nIkcoREWsM8H5QMjeN++0KlDBlLWnulqhvbQJXaR6Gq
  template:
    metadata:
      creationTimestamp: null
      name: selection-list-secrets
      namespace: fuzefront
    type: Opaque
