/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/security/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current identity ("me")
         * @description Returns the normalized `Identity` and hydrated user for the presented session token. This is the source of any out-of-band role/tenant hydration in legacy token mode.
         */
        get: operations["getSession"];
        put?: never;
        /**
         * Password login — establish a session
         * @description Validates credentials via the configured identity provider (server- brokered; the browser never leaves `app.fuzefront.com`) and returns a FuzeFront-minted session token plus the hydrated user. Fail-closed on bad credentials.
         */
        post: operations["createSession"];
        /** Logout — revoke the current session */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/session/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an opaque broker code for a session
         * @description Exchanges the FuzeFront-minted opaque `code` issued by `GET /v1/security/social/callback` for a session token. The code is single-use and short-lived. Fail-closed on an unknown/expired code.
         */
        post: operations["exchangeSessionCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/social/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin social login (302)
         * @description Initiates a server-brokered social login handshake and 302-redirects the browser to the social provider's own consent host via a FuzeFront-owned, same-host authorize path. No internal identity host is ever exposed. On completion the provider returns to `GET /v1/security/social/callback`.
         */
        get: operations["startSocialLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/social/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Social login broker callback (302 back to app)
         * @description The server broker completes the social handshake, provisions/links the user, mints a single-use opaque code, and 302-redirects the browser back to the app with `?code=<opaque>`. The SPA then calls `POST /v1/security/session/exchange`. No token is placed in the URL.
         */
        get: operations["socialCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account (server-brokered)
         * @description Server-brokered account creation via the configured identity provider. The user only ever sees FuzeFront-branded UI — never a provider's raw enrollment page. On success a session may be established directly.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth capability descriptor
         * @description Neutral capability descriptor for the auth surface. Replaces the legacy vendor-specific `oidcConfigured` boolean. Lets the UI render the right affordances (password form, social buttons) without knowing any provider.
         */
        get: operations["getAuthMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/authz/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authorization check (single)
         * @description Returns whether `subject` may perform `action` on `resource` within `tenant`. Fail-closed: any provider/transport error returns `{ allow: false }` (never an exception surfaced as allow).
         */
        post: operations["authzCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/authz/bulk-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authorization check (bulk)
         * @description Evaluates an ordered list of checks and returns decisions in the same order. Fail-closed per element. The number of decisions equals the number of requested checks. Bounded by the caller-supplied input array (`maxItems`), so no server-side pagination applies.
         */
        post: operations["authzBulkCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/authz/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Effective permissions for a subject in a tenant
         * @description Returns the effective permission set for `subject` scoped to `tenant`. The permission set for a single subject within one tenant is bounded by the policy model (a fixed catalogue of resource/action pairs), not by user-controlled data growth, so it is returned whole.
         */
        get: operations["getPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tenants visible to the caller
         * @description Unbounded collection — cursor-paginated per the family pagination standard.
         */
        get: operations["listTenants"];
        put?: never;
        /** Create a tenant */
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/tenants/{tenantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tenant */
        get: operations["getTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/tenants/{tenantId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List members of a tenant
         * @description Unbounded collection — cursor-paginated per the family pagination standard.
         */
        get: operations["listTenantMembers"];
        put?: never;
        /** Add a member to a tenant */
        post: operations["addTenantMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/tenants/{tenantId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from a tenant */
        delete: operations["removeTenantMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/tenants/{tenantId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List roles defined for a tenant
         * @description Roles are a bounded, policy-defined catalogue per tenant (not user-data-driven), so the full set is returned.
         */
        get: operations["listTenantRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/tenants/{tenantId}/members/{userId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Assign roles to a member
         * @description Replaces the member's role assignment within the tenant.
         */
        put: operations["assignMemberRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue an M2M token
         * @description Issues a FuzeFront-owned machine-to-machine token for a provisioned service client (client-credentials style). The issuing identity provider is hidden behind the adapter.
         */
        post: operations["issueToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/security/tokens/introspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Introspect an M2M token
         * @description Returns the active state and normalized claims for a presented M2M token. Fail-closed: an unknown/expired token returns `{ active: false }`.
         */
        post: operations["introspectToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Password login credentials. Shape-compatible with today's login. */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @description Session established. Kept shape-compatible with today's login response (adds `sessionId`) so the frontend rename is mechanical. */
        LoginResponse: {
            /** @description FuzeFront-minted session token. */
            token: string;
            /** @description Server session identifier. */
            sessionId?: string;
            user: components["schemas"]["User"];
        };
        SignupRequest: {
            /** Format: email */
            email: string;
            password: string;
            firstName?: string;
            lastName?: string;
            /** @description Optional tenant/organization name to provision on signup. */
            tenantName?: string;
        };
        ExchangeRequest: {
            /** @description The single-use opaque code from the social callback redirect. */
            code: string;
        };
        /** @description Current identity plus hydrated user. */
        SessionInfo: {
            identity: components["schemas"]["Identity"];
            user: components["schemas"]["User"];
        };
        /** @description Neutral auth capability descriptor. Replaces `oidcConfigured`. */
        AuthMethods: {
            /** @description Whether password login/signup is available. */
            password: boolean;
            /** @description Enabled social provider slugs (may be empty). */
            social: components["schemas"]["SocialProvider"][];
        };
        /**
         * @description Supported social provider slug. Extensible; `google` is first.
         * @enum {string}
         */
        SocialProvider: "google";
        /** @description Hydrated user (source of out-of-band role/tenant resolution). */
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            firstName?: string;
            lastName?: string;
            defaultAppId?: string;
            roles: string[];
        };
        /** @description The STABLE normalized identity, invariant across token-format migrations. Mirrors the TypeScript `Identity` interface in `@fuzefront/security-client`. Provider-neutral. */
        Identity: {
            /** @description Stable subject id. Always present. */
            userId: string;
            /** @description Tenant/org scope. May be null in legacy token mode when unresolved. Consumers fail-closed on tenant-scoped authz when null. */
            tenantId: string | null;
            /** @description Always an array; empty means "no roles known". */
            roles: string[];
            email?: string;
            /** @enum {string} */
            authMode: "legacy-hs256" | "federated-jwks";
            issuedAt?: number;
            expiresAt?: number;
            issuer?: string;
        };
        AuthzCheckRequest: {
            /** @description The principal id (user or service client). */
            subject: string;
            /** @description Tenant/org scope for the decision. */
            tenant: string;
            resource: components["schemas"]["ResourceRef"];
            action: string;
            context?: {
                [key: string]: unknown;
            };
        };
        ResourceRef: {
            type: string;
            /** @description Optional specific resource instance key. */
            key?: string;
        };
        AuthzDecision: {
            allow: boolean;
        };
        AuthzBulkCheckRequest: {
            checks: components["schemas"]["AuthzCheckRequest"][];
        };
        AuthzBulkDecision: {
            /** @description Index-aligned with the request `checks`. */
            decisions: components["schemas"]["AuthzDecision"][];
        };
        PermissionSet: {
            subject: string;
            tenant: string;
            /** @description Effective `resource:action` grants. */
            permissions: string[];
        };
        Tenant: {
            id: string;
            name: string;
            slug?: string;
        };
        TenantCreate: {
            name: string;
            slug?: string;
        };
        Member: {
            userId: string;
            email?: string;
            roles: string[];
        };
        MemberCreate: {
            userId?: string;
            email?: string;
            roles?: string[];
        };
        Role: {
            key: string;
            name?: string;
        };
        RoleAssignment: {
            roles: string[];
        };
        TokenIssueRequest: {
            clientId: string;
            clientSecret: string;
            scope?: string;
        };
        TokenIssueResponse: {
            accessToken: string;
            /** @default Bearer */
            tokenType: string;
            /** @description Lifetime in seconds. */
            expiresIn: number;
            scope?: string;
        };
        TokenIntrospectRequest: {
            token: string;
        };
        /** @description Fail-closed introspection result. */
        TokenIntrospection: {
            active: boolean;
            subject?: string;
            tenantId?: string | null;
            scope?: string;
            expiresAt?: number;
        };
        /** @description Cursor-pagination page metadata (family standard). */
        PageInfo: {
            /** @description Opaque cursor for the next page; null on the last page. */
            nextCursor: string | null;
            hasMore: boolean;
            /** @description Optional; omitted when counting the full set is expensive. */
            total?: number;
        };
        TenantPage: {
            items: components["schemas"]["Tenant"][];
            page: components["schemas"]["PageInfo"];
        };
        MemberPage: {
            items: components["schemas"]["Member"][];
            page: components["schemas"]["PageInfo"];
        };
        /** @description Stable error body. Fail-closed; provider-neutral codes. */
        ErrorBody: {
            error: string;
            /** @enum {string} */
            code: "NO_TOKEN" | "MALFORMED" | "INVALID_SIGNATURE" | "EXPIRED" | "NOT_ACTIVE" | "INVALID_ISSUER" | "INVALID_AUDIENCE" | "MISSING_CLAIM" | "JWKS_UNAVAILABLE" | "VERIFIER_UNAVAILABLE" | "INVALID_CREDENTIALS" | "INVALID_CODE" | "CONFLICT" | "FORBIDDEN" | "NOT_FOUND" | "PROVIDER_UNAVAILABLE" | "UNKNOWN";
        };
    };
    responses: {
        /** @description Authentication failed (fail-closed). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: {
        /** @description Max items per page. Clamped server-side to the maximum. */
        Limit: number;
        /** @description Opaque, server-issued cursor for the next page. Omit for the first page. */
        Cursor: string;
        TenantId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current identity + user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; token, user, and session id returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    exchangeSessionCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeRequest"];
            };
        };
        responses: {
            /** @description Session established. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    startSocialLogin: {
        parameters: {
            query?: {
                /** @description Optional app-relative path to return to after login completes. Must be same-origin; absolute URLs are rejected. */
                redirectTo?: string;
            };
            header?: never;
            path: {
                /** @description Social provider slug. Extensible; `google` is the first supported value. */
                provider: components["schemas"]["SocialProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the social provider consent flow. */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    socialCallback: {
        parameters: {
            query: {
                /** @description Provider authorization code (protocol-level; consumed server-side). */
                code: string;
                /** @description Opaque anti-forgery state issued at start. */
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect back to the app with a FuzeFront opaque `?code=`. */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Account created; session established. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description An account with that email already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getAuthMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The configured auth capabilities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMethods"];
                };
            };
        };
    };
    authzCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthzCheckRequest"];
            };
        };
        responses: {
            /** @description The decision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthzDecision"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    authzBulkCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthzBulkCheckRequest"];
            };
        };
        responses: {
            /** @description Decisions, index-aligned with the request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthzBulkDecision"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getPermissions: {
        parameters: {
            query: {
                subject: string;
                tenant: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The effective permissions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionSet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listTenants: {
        parameters: {
            query?: {
                /** @description Max items per page. Clamped server-side to the maximum. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque, server-issued cursor for the next page. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of tenants. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCreate"];
            };
        };
        responses: {
            /** @description Tenant created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTenantMembers: {
        parameters: {
            query?: {
                /** @description Max items per page. Clamped server-side to the maximum. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque, server-issued cursor for the next page. Omit for the first page. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addTenantMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreate"];
            };
        };
        responses: {
            /** @description Member added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    removeTenantMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantId"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTenantRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tenant's roles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Role"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    assignMemberRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: components["parameters"]["TenantId"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAssignment"];
            };
        };
        responses: {
            /** @description Roles updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    issueToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenIssueRequest"];
            };
        };
        responses: {
            /** @description Token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenIssueResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    introspectToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenIntrospectRequest"];
            };
        };
        responses: {
            /** @description Introspection result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenIntrospection"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
}
