/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/portal/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve the public context for the current portal
         * @description Returns the active portal's public boot data (id, slug, branding, identity policy, auth entry points) for the Host/`/p/<slug>`/custom domain the request arrived on. **Unauthenticated** — it must render before login so a branded login screen can paint. Exposes only public branding/identity-policy/auth-entry fields; never a raw `portals` row. Fail-closed: an unknown host resolves to the root portal (for shell/UI routes), and a suspended portal returns 403 `PORTAL_SUSPENDED`.
         */
        get: operations["getPortalContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portal/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the caller's own portal
         * @description Returns the full portal record for the portal the authenticated caller belongs to, resolved from the session/token (`req.user.portalId`) — a `portalId` is **never** accepted from the client. Used by the portal-admin console to render portal identity (domain, owner, status). A caller acting on a portal they do not administer gets 403 `FORBIDDEN_PORTAL`.
         */
        get: operations["getCurrentPortal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/portals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List portals (master-admin fleet view)
         * @description Returns a cursor-paginated page of portals for the master-admin fleet list. A fresh install returns exactly one portal (the seeded root portal, slug `fuzefront`).
         *     When `fuzefront.platform.portals-directory` is OFF, this stays Permit **platform-admin** only — a non-admin caller is denied fail-closed with 403 `FORBIDDEN`, byte-identical to the pre-1.3.0 contract.
         *     When the flag is ON (backend slice S5), the blanket admin-only gate is replaced by a per-portal Permit `read`/`manage` check on each portal's owning organization (`Organization:read` / `Organization:manage`, including the parent-org `org-admin` derivation for platform/master admins): a caller with `manage` on a portal's org sees it with `canManage: true, canOpen: true` and a `launchUrl`; a caller with only `read` sees it read-only (`canManage: false, canOpen: false`, no `launchUrl`); a portal the caller cannot even `read` is never returned (BOLA-safe filtering, never after-the-fact leakage). A caller with `read` authority over NONE of the portals this query would otherwise return still gets the fail-closed 403 `FORBIDDEN` no-access response — the read-vs-manage refinement only ever WIDENS who sees a 200 relative to the pre-flag blanket gate, never who is denied.
         */
        get: operations["listPortals"];
        put?: never;
        /**
         * Create (provision) a portal
         * @description Provisions a new tenant portal via the resumable pipeline (org → Permit tenant → portal row → default subdomain → owner invite). The new portal starts `provisioned-pending-invite` (never silently `active`) and the owner invite dispatches with provisioning. `slug` is immutable and must be unique — a duplicate returns 409 `SLUG_TAKEN`. Permit **platform-admin** only.
         */
        post: operations["createPortal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/portals/{portalId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The portal's server-issued id (e.g. `prt_northwind`). */
                portalId: components["parameters"]["PortalId"];
            };
            cookie?: never;
        };
        /**
         * Get a portal by id
         * @description Returns the full portal record (branding, identity policy, billing mode, domains + verification/TLS status). Permit **platform-admin** only.
         */
        get: operations["getPortal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a portal (fields and/or lifecycle status)
         * @description Partially updates a portal. `name`, `branding`, `identityPolicy`, and `billingMode` are mutable; `slug` is immutable and cannot be changed. Setting `status` is how the master-admin **suspends** (`active` → `suspended`) or **resumes** (`suspended` → `active`) a portal — this is the transition the fleet list and detail views bind to. Suspending the root portal (slug `fuzefront`) is refused with 409 `ROOT_PORTAL_PROTECTED`. Permit **platform-admin** only. Equivalent semantic action endpoints are `POST .../suspend` and `POST .../resume`.
         */
        patch: operations["updatePortal"];
        trace?: never;
    };
    "/api/v1/admin/portals/{portalId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The portal's server-issued id (e.g. `prt_northwind`). */
                portalId: components["parameters"]["PortalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspend a portal
         * @description Semantic lifecycle action equivalent to `PATCH .../{portalId}` with `{ "status": "suspended" }`. Flips the portal to `suspended`, after which it fails closed (paired with FF-EPIC-10 resolution: 403 `PORTAL_SUSPENDED`) and any cached resolution is invalidated. Idempotent: suspending an already-suspended portal is a no-op 200. Suspending the root portal is refused with 409 `ROOT_PORTAL_PROTECTED`. Permit **platform-admin** only.
         */
        post: operations["suspendPortal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/portals/{portalId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The portal's server-issued id (e.g. `prt_northwind`). */
                portalId: components["parameters"]["PortalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume a suspended portal
         * @description Semantic lifecycle action equivalent to `PATCH .../{portalId}` with `{ "status": "active" }`. Flips a `suspended` portal back to `active` and invalidates any cached resolution. Idempotent: resuming an already-active portal is a no-op 200. Permit **platform-admin** only.
         */
        post: operations["resumePortal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness / readiness
         * @description Unauthenticated liveness/readiness probe for the portal surface.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Server-issued portal id, immutable once provisioned.
         * @example prt_fuzefront
         * @example prt_northwind
         */
        PortalId: string;
        /**
         * @description URL-safe unique portal identifier used for `/p/<slug>` and the default subdomain, immutable once provisioned. The root portal's slug is `fuzefront`.
         * @example fuzefront
         * @example northwind
         */
        Slug: string;
        /**
         * @description Lifecycle status. `provisioning` and `provisioned-pending-invite` are transient states from the resumable provisioning pipeline (FF-EPIC-09-S2); `active`/`suspended` are the steady lifecycle the master-admin toggles.
         * @enum {string}
         */
        PortalStatus: "provisioning" | "provisioned-pending-invite" | "active" | "suspended";
        /**
         * @description Whether the portal shares the root FuzeFront Authentik directory (`soft`, the default for every ordinary portal) or owns a dedicated Authentik instance (`hard` — its own directory, DB, ingress host, and blueprint set; e.g. the MendysRobotics tenant). Currently populated ONLY on `GET /api/v1/admin/portals` (the master-admin fleet list), behind `fuzefront.platform.portals-directory` (default OFF) — absent elsewhere until other portal endpoints adopt it.
         * @enum {string}
         */
        IdentityMode: "soft" | "hard";
        /**
         * @description How the portal is billed. `free` — no billing; `platform` — billed by FuzeFront directly; `reseller` — the portal bills its own users via Stripe Connect (FF-EPIC-15). Selecting `reseller` at create time unlocks the Connect console.
         * @enum {string}
         */
        BillingMode: "free" | "platform" | "reseller";
        /**
         * @description How a portal is addressed. `subdomain` (e.g. `northwind.fuzefront.com`), `path` (`/p/northwind`), or a verified `custom` domain (FF-EPIC-16).
         * @enum {string}
         */
        DomainKind: "subdomain" | "path" | "custom";
        /**
         * @description Domain-ownership verification status (custom domains, FF-EPIC-16).
         *     Sourced from FuzeInfra's `dns_status`, NOT from a FuzeFront-issued TXT token. We deliberately do not generate a `_fuzefront-verify` record and do not poll DNS: Cloudflare issues `_cf-custom-hostname.<domain>` and validates it itself, which is the same proof of DNS control checked by the party that also issues the certificate — and one fewer record for the customer to publish.
         *     * `pending` — records not yet published or propagated * `verified` — ownership proven and the domain resolves to the platform * `moved` — the domain stopped pointing at us * `blocked` — refused upstream; the hostname is claimed elsewhere * `failed` — validation failed; see `error`
         * @enum {string}
         */
        VerificationStatus: "pending" | "verified" | "moved" | "blocked" | "failed";
        /**
         * @description Certificate lifecycle for the domain, mirroring FuzeInfra's normalized `tls_status` enum verbatim (contract: `services/custom-hostname-api/openapi.yaml`). Those values are already mapped from Cloudflare's rawer vocabulary, and unknown upstream states deliberately map to a pending state rather than to a failure — so a Cloudflare vocabulary change cannot present to a user as an error. Re-mapping them here would only re-introduce the coupling FuzeInfra removed.
         *     Everything before `active` is a normal in-progress state. `failed` and `expired` are terminal until the customer fixes their DNS; retry is a re-POST.
         *     `none` is FuzeFront-only: a `subdomain`/`path` domain served by the static wildcard certificate, which needs no per-domain issuance.
         * @enum {string}
         */
        TlsStatus: "none" | "pending_validation" | "pending_issuance" | "pending_deployment" | "active" | "expired" | "failed";
        /** @description Public white-label branding, applied entirely through design-system token overrides (no raw hex in feature code). Every field has a documented fallback so the UI never shows a broken image or unbranded flash. */
        PortalBranding: {
            /** @description Portal display name (e.g. "Northwind"). Shown in the topbar and login. */
            name: string;
            /**
             * Format: uri
             * @description Logo image URL, or null → initials/default fallback (never a broken image).
             */
            logo?: string | null;
            /**
             * Format: uri
             * @description Favicon URL, or null → default fallback (cache-busted per portal id).
             */
            favicon?: string | null;
            /** @description CSS color applied as a scoped design-system token override (`--accent-*`). AA-contrast-validated; a malformed color falls back to the default accent. Null → default. */
            accent?: string | null;
            /** @description Optional custom login copy / strapline. Null → default copy. */
            tagline?: string | null;
        };
        /** @description Public identity policy telling the login screen which auth affordances to render. Contains no secrets — only booleans and public provider ids. */
        PortalIdentityPolicy: {
            /** @description Whether email/password sign-in is offered. */
            allowPasswordLogin: boolean;
            /** @description Whether the "create account" affordance is shown. */
            allowSelfSignup: boolean;
            /**
             * @description Whether MFA is enforced for this portal.
             * @default false
             */
            mfaRequired: boolean;
            /** @description Public SSO provider ids offered on this portal (e.g. `google`, `okta`). */
            ssoProviders?: string[];
            /**
             * @description FF-EPIC-11-S5 — internal/admin-only opt-in allowing a platform (root-org) administrator to authenticate into this tenant portal for support purposes, bypassing the normal home-portal-based cross-portal login rejection. Every exercise of this path is audit-logged. Default false/absent — a portal must explicitly opt in. Never returned on the PUBLIC, pre-auth `GET /api/v1/portal/context` boot payload (only surfaced on authenticated admin portal-management responses) — despite sharing this schema, that specific projection whitelists only the fields above.
             * @default false
             */
            allowPlatformAdminSupportAccess: boolean;
        };
        /** @description A single SSO button on the login screen. */
        PortalSsoProvider: {
            /** @description Stable provider id (e.g. `google`). */
            id: string;
            /** @description Human label (e.g. "Continue with Google"). */
            label: string;
            /**
             * Format: uri-reference
             * @description Same-origin URL that begins the SSO flow for this portal.
             */
            startUrl: string;
        };
        /** @description Where the shell/login sends the user to authenticate — all same-origin so it works identically under local TLS and prod ingress. */
        PortalAuthEntry: {
            /**
             * Format: uri-reference
             * @description Same-origin login route for this portal.
             */
            loginUrl: string;
            /**
             * Format: uri-reference
             * @description Create-account route, or null when self-signup is disabled.
             */
            signupUrl?: string | null;
            /**
             * Format: uri-reference
             * @description Password-reset route, or null when password login is disabled.
             */
            forgotPasswordUrl?: string | null;
            /** @description SSO buttons to render, in display order. */
            ssoProviders?: components["schemas"]["PortalSsoProvider"][];
        };
        /** @description The public boot payload for `GET /api/v1/portal/context`. Intentionally a narrow, public projection of a portal — id, slug, branding, identity policy, and auth entry — never a raw `portals` row. */
        PortalContext: {
            id: components["schemas"]["PortalId"];
            slug: components["schemas"]["Slug"];
            /**
             * @description True when this is the seeded root portal (unknown-host fallback).
             * @default false
             */
            isRoot: boolean;
            branding: components["schemas"]["PortalBranding"];
            identityPolicy: components["schemas"]["PortalIdentityPolicy"];
            authEntry: components["schemas"]["PortalAuthEntry"];
        };
        /**
         * @description A domain (subdomain / path / custom) bound to a portal, with its verification + TLS status. Add/verify of custom domains is FF-EPIC-16; here domains are read-only.
         *     For `kind: custom`, every status field is a projection of FuzeInfra's Custom Hostname API response — see `services/custom-hostname-api/`.
         */
        PortalDomain: {
            id: string;
            portalId: components["schemas"]["PortalId"];
            /** @description The host or path segment (e.g. `northwind.fuzefront.com` or `northwind`). */
            domain: string;
            kind: components["schemas"]["DomainKind"];
            verificationStatus: components["schemas"]["VerificationStatus"];
            tlsStatus: components["schemas"]["TlsStatus"];
            /**
             * @description **The only field to gate on** before advertising this domain to a user. True only when DNS validation passed, the certificate is deployed, AND the in-cluster routing exists. Any one missing means a visitor gets an error, so the three are deliberately collapsed into one boolean rather than left for each caller to re-derive.
             *     Notably NOT equivalent to `tlsStatus == active`: a certificate can be live while routing is missing, which serves a valid certificate in front of a 404.
             *     Always true for `subdomain`/`path` domains, which the static wildcard already serves.
             */
            active: boolean;
            /** @description Whether this is the portal's primary/canonical domain. */
            isPrimary: boolean;
            /**
             * @description DNS records the customer must publish, for `kind: custom` only. Sourced from the upstream `verification.records[]` — FuzeFront does not mint its own verification token.
             *     A UI must render ALL of these. The ownership record alone is not enough to make the domain work.
             */
            verificationRecords?: components["schemas"]["DomainVerificationRecord"][];
            /** @description The hostname the customer CNAMEs their domain to. Always read from the API rather than hard-coded: the target is a deliberate public contract kept separate from the origin, so the origin can be repointed without asking every customer to change DNS. */
            cnameTarget?: string | null;
            /** @description Human-readable reason when a status is failed/blocked. Shown with a retry action. */
            error?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description One DNS record the customer must publish for a custom domain. */
        DomainVerificationRecord: {
            /** @enum {string} */
            method: "txt" | "cname";
            /** @description The record NAME to create. */
            record: string;
            /** @description The record VALUE. */
            value: string;
            /**
             * @description `ownership` proves domain control (`_cf-custom-hostname.<domain>`), `certificate` satisfies ACME DCV (`_acme-challenge.<domain>`), and `routing` points traffic at us (CNAME). Presented in that order — a customer migrating a live domain publishes the TXT records first and cuts the CNAME over last, which is what makes the migration zero-downtime.
             * @enum {string}
             */
            purpose: "ownership" | "certificate" | "routing";
        };
        /** @description The full portal record returned by the master-admin CRUD and `GET /api/v1/portal/current`. Its `status` field is the single source of truth for the fail-closed block that pairs with FF-EPIC-10 resolution. */
        Portal: {
            id: components["schemas"]["PortalId"];
            slug: components["schemas"]["Slug"];
            name: string;
            status: components["schemas"]["PortalStatus"];
            /**
             * @description True for the seeded root portal (slug `fuzefront`) — cannot be suspended.
             * @default false
             */
            isRoot: boolean;
            /**
             * Format: uuid
             * @description The tenant organization backing this portal (unique 1:1).
             */
            organizationId: string;
            /**
             * Format: email
             * @description The portal owner's email (from the create/invite step).
             */
            ownerEmail?: string | null;
            billingMode: components["schemas"]["BillingMode"];
            branding: components["schemas"]["PortalBranding"];
            identityPolicy: components["schemas"]["PortalIdentityPolicy"];
            /** @description Domains bound to this portal (read-only here). */
            domains: components["schemas"]["PortalDomain"][];
            /** @description Convenience: the primary domain string, or null if none yet. */
            primaryDomain?: string | null;
            /** @description OPTIONAL — only present on `GET /api/v1/admin/portals` (list) responses, and only when `fuzefront.platform.portals-directory` is enabled for the caller. See `IdentityMode` for the field's own description. Absent (not `null`) on every other portal response. Present on EVERY row the caller may see (read-only or manage — see `canManage`/`canOpen` below). */
            identityMode?: components["schemas"]["IdentityMode"];
            /** @description OPTIONAL (backend slice S5, read-vs-no-access refinement) — only present on `GET /api/v1/admin/portals` (list) responses when `fuzefront.platform.portals-directory` is enabled. Whether the caller holds Permit `manage` authority (not just `read`) on this portal's owning organization — derived via the existing `Organization` resource's `read`/`manage` actions and the parent-org `org-admin` ReBAC derivation (platform/master admins included). `false` renders the row read-only in the directory UI (no manage/launch affordance). Absent (not present at all) when the flag is OFF. */
            canManage?: boolean;
            /** @description OPTIONAL — same gating as `canManage` above. The authority to LAUNCH the portal. There is no separate Permit `open`/`launch` action on `Organization` today, so this intentionally mirrors `canManage` — a caller who can manage a portal can also launch it, and a read-only viewer can neither. If a distinct launch authority is ever introduced this field decouples from `canManage` without a contract break (it is already its own field). Absent when the flag is OFF. */
            canOpen?: boolean;
            /**
             * Format: uri
             * @description OPTIONAL — present on `GET /api/v1/admin/portals` (list) responses only when `fuzefront.platform.portals-directory` is enabled AND `canOpen` is `true` for this row. Absent (not `null`, not present at all) for a read-only row (`canOpen: false`) — a caller without launch authority must never receive the launch host. `https://<primary domain>` when the portal has a primary `portal_domains` row, else the platform-owned default subdomain (`https://<slug>.fuzefront.com`) `default_domain_create` provisions for every portal.
             */
            launchUrl?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Payload to provision a new portal. */
        PortalCreate: {
            name: string;
            slug: components["schemas"]["Slug"];
            /**
             * Format: email
             * @description The email invited as the portal owner during provisioning.
             */
            ownerEmail: string;
            /** @default free */
            billingMode: components["schemas"]["BillingMode"];
            branding?: components["schemas"]["PortalBranding"];
            identityPolicy?: components["schemas"]["PortalIdentityPolicy"];
        };
        /** @description Partial update. All fields optional; at least one must be present. `slug` is immutable and is intentionally absent. Setting `status` performs suspend/resume. */
        PortalUpdate: {
            name?: string;
            status?: components["schemas"]["PortalStatus"];
            billingMode?: components["schemas"]["BillingMode"];
            branding?: components["schemas"]["PortalBranding"];
            identityPolicy?: components["schemas"]["PortalIdentityPolicy"];
        };
        /** @description Cursor-pagination envelope (canonical, `governance/pagination-standard.md`). */
        Page: {
            /** @description Opaque cursor for the next page, or null on the last page. */
            nextCursor: string | null;
            /** @description Whether a further page exists. */
            hasMore: boolean;
            /** @description Optional total count (omitted when counting is expensive). */
            total?: number;
        };
        /** @description A page of portals — the `{ items, page }` envelope. */
        PortalPage: {
            items: components["schemas"]["Portal"][];
            page: components["schemas"]["Page"];
        };
        /** @description Stable machine-readable error. `error` codes used by this contract: `PORTAL_SUSPENDED`, `ROOT_PORTAL_PROTECTED`, `SLUG_TAKEN`, `FORBIDDEN`, `FORBIDDEN_PORTAL`, `NOT_FOUND`, `UNAUTHORIZED`, `INTERNAL`. */
        ErrorBody: {
            /** @description Stable machine-readable error code. */
            error: string;
            /** @description Human-readable detail. */
            message?: string;
        };
        ValidationErrorBody: {
            /** @enum {string} */
            error: "validation_error";
            message?: string;
            fields: {
                path: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description Missing or invalid session / token (re-authenticate). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description The caller is not a platform admin (`FORBIDDEN`). An authorization denial, never a sign-in redirect. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description The caller acted on a portal they do not administer (`FORBIDDEN_PORTAL`) — no cross-tenant data is returned. */
        ForbiddenPortal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Portal not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Request body failed validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorBody"];
            };
        };
        /** @description Unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: {
        /** @description The portal's server-issued id (e.g. `prt_northwind`). */
        PortalId: components["schemas"]["PortalId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPortalContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The resolved portal context. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalContext"];
                };
            };
            /** @description The resolved portal is suspended (`PORTAL_SUSPENDED`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getCurrentPortal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's portal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portal"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["ForbiddenPortal"];
            500: components["responses"]["InternalError"];
        };
    };
    listPortals: {
        parameters: {
            query?: {
                /** @description Filter by lifecycle status. Omit for all statuses. */
                status?: components["schemas"]["PortalStatus"];
                /** @description Free-text filter over name/slug/primary domain. */
                q?: string;
                /** @description Page size. Clamped to `maximum` server-side. */
                limit?: number;
                /** @description Opaque, server-issued pagination cursor (from `page.nextCursor`). */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of portals. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Portal"][];
                        page: components["schemas"]["Page"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createPortal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalCreate"];
            };
        };
        responses: {
            /** @description Portal created (status = provisioned-pending-invite). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portal"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A portal with this slug already exists (`SLUG_TAKEN`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getPortal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The portal's server-issued id (e.g. `prt_northwind`). */
                portalId: components["parameters"]["PortalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The portal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portal"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updatePortal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The portal's server-issued id (e.g. `prt_northwind`). */
                portalId: components["parameters"]["PortalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalUpdate"];
            };
        };
        responses: {
            /** @description The updated portal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portal"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The requested transition is refused — e.g. suspending the root portal (`ROOT_PORTAL_PROTECTED`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    suspendPortal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The portal's server-issued id (e.g. `prt_northwind`). */
                portalId: components["parameters"]["PortalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portal suspended. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portal"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The root portal cannot be suspended (`ROOT_PORTAL_PROTECTED`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    resumePortal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The portal's server-issued id (e.g. `prt_northwind`). */
                portalId: components["parameters"]["PortalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portal resumed (active). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portal"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
