{{- if .Values.configService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: fuzefront-config-service
  labels:
    {{- include "fuzefront.labels" . | nindent 4 }}
    app.kubernetes.io/component: config-service
spec:
  selector:
    app: fuzefront-config-service
  ports:
    - port: {{ .Values.configService.port }}
      targetPort: {{ .Values.configService.port }}
      protocol: TCP
      name: http
{{- end }}
