/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List registered apps
         * @description Returns the apps visible to the caller, filtered by the caller's org/roles and the requested `status`/`mode`. The host launcher and side menu call this to render the application menu. Replaces the legacy unfiltered `GET /api/apps`.
         */
        get: operations["listApps"];
        put?: never;
        /**
         * Register an app
         * @description Registers a new app from its **manifest**. The app starts in `registered` status (NOT visible) — it must be activated to appear in the menu. The `slug` must be unique. Requires the `apps:register` scope (platform-admin or org-admin per visibility). Emits `app.registered`.
         */
        post: operations["registerApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The app's immutable url-safe slug (e.g. `clock`). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        /**
         * Get an app by slug
         * @description Returns the full app record (including its manifest).
         */
        get: operations["getApp"];
        /**
         * Replace an app's manifest
         * @description Replaces the manifest of an existing app. `slug`, `builtin`, and `manifestVersion` are immutable and must match. Requires `apps:write`.
         */
        put: operations["updateApp"];
        post?: never;
        /**
         * Delete a registered app
         * @description Permanently removes a registered app. **Built-in apps cannot be deleted** (only suspended) — returns 403. Requires `apps:write`.
         */
        delete: operations["deleteApp"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{slug}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The app's immutable url-safe slug (e.g. `clock`). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate an app
         * @description Transitions an app to `activated` so it appears in the application menu / launcher. Idempotent: activating an already-activated app is a no-op 200. Requires `apps:activate`. Emits `app.activated`.
         */
        post: operations["activateApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{slug}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The app's immutable url-safe slug (e.g. `clock`). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspend an app
         * @description Transitions an app to `suspended` (hidden from the menu, record retained). Works for built-in apps too. Idempotent. Requires `apps:activate`. Emits `app.suspended`.
         */
        post: operations["suspendApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{slug}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The app's immutable url-safe slug (e.g. `clock`). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report app liveness
         * @description Called by a running app (or its SDK) to report liveness. Authenticated by a per-app heartbeat token, not a user session. Updates `lastSeenAt` and emits `app.heartbeat`. Mirrors the legacy `POST /api/apps/:id/heartbeat`.
         */
        post: operations["heartbeatApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness / readiness */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description URL-safe unique identifier, immutable once registered. */
        Slug: string;
        /**
         * @description `portal` — mounted inside the host shell at `/app/:slug` with chrome. `standalone` — rendered without portal chrome on its own host/path.
         * @enum {string}
         */
        AppMode: "portal" | "standalone";
        /**
         * @description Lifecycle status. registered → activated → suspended.
         * @enum {string}
         */
        AppStatus: "registered" | "activated" | "suspended";
        /** @enum {string} */
        IntegrationType: "module-federation" | "iframe" | "web-component" | "spa";
        /** @enum {string} */
        Visibility: "private" | "organization" | "public" | "marketplace";
        /** @description App icon — either an emoji glyph or an image URL. */
        Icon: {
            /** @enum {string} */
            kind: "emoji" | "url";
            /** @description The emoji character, or an https URL to the icon image. */
            value: string;
        };
        /** @description How the host loads/mounts the app. */
        Integration: {
            type: components["schemas"]["IntegrationType"];
            /**
             * Format: uri
             * @description FULL Module-Federation remote entry URL, e.g. `https://clock.example.com/remoteEntry.js`. Required when `type = module-federation`. This freezes the legacy base-vs-entry ambiguity: the value is the complete entry URL, NOT a base.
             */
            remoteEntry?: string;
            /** @description MF remote scope/name. Required for module-federation. */
            scope?: string;
            /** @description Exposed module path, e.g. `./ClockApp`. Required for module-federation. */
            module?: string;
            /**
             * Format: uri
             * @description Navigable URL for `iframe` and `standalone`/`spa` integrations.
             */
            url?: string;
        };
        /** @description An app-declared menu item (for chrome substitution or app section). */
        MenuItem: {
            id: string;
            label: string;
            /** @description icon name or emoji */
            icon?: string;
            /** @description in-app route the item navigates to */
            route?: string;
            order?: number;
        };
        /** @description How the host's chrome behaves while this app is active. Ignored for `mode = standalone` (standalone apps render with no portal chrome). */
        Chrome: {
            /**
             * @description `host` — keep the portal side menu (app may still push runtime items). `substitute` — the app provides its OWN full side menu; the host yields its portal menu and renders `items` instead. The host always retains a minimal "return to portal" affordance so the user is never trapped.
             * @default host
             * @enum {string}
             */
            menu: "host" | "substitute";
            /**
             * @default host
             * @enum {string}
             */
            topbar: "host" | "hidden";
            /** @description App-declared menu items, used when `menu = substitute`. */
            items?: components["schemas"]["MenuItem"][];
        };
        /** @description Routing for the app. `host` applies to standalone only. */
        Routing: {
            /** @description Path the app is reachable at. For portal apps this is informational (host mounts at `/app/:slug`); for standalone it is the routed path. */
            path?: string;
            /** @description Standalone-only: a dedicated host (e.g. `clock.fuzefront.com`). When omitted, standalone apps are path-based under the main app host. */
            host?: string;
        };
        /** @description Platform infrastructure the (typically standalone) app opts into. Portal apps implicitly get auth + api; this block is mainly meaningful for standalone apps that selectively use FuzeFront infra. */
        Infra: {
            /**
             * @description Authentik identity/SSO
             * @default true
             */
            auth: boolean;
            /**
             * @description Stripe billing surface
             * @default false
             */
            billing: boolean;
            /**
             * @description Same-origin platform API
             * @default true
             */
            api: boolean;
            /**
             * @description Deployed via the FuzeInfra GitOps pipeline
             * @default true
             */
            deployOnFuzeInfra: boolean;
        };
        /** @description The declarative document describing how the host mounts and chromes an app. Stored on the app row, served back on read, and the single shared type across UI / backend / tests. */
        AppManifest: {
            /** @enum {string} */
            manifestVersion: "1";
            slug: components["schemas"]["Slug"];
            name: string;
            /** @description Label shown in the application menu / launcher (e.g. "Market"). */
            menuLabel: string;
            description?: string;
            icon?: components["schemas"]["Icon"];
            mode: components["schemas"]["AppMode"];
            /**
             * @description Shipped with the platform; cannot be deleted, only suspended.
             * @default false
             */
            builtin: boolean;
            integration: components["schemas"]["Integration"];
            chrome?: components["schemas"]["Chrome"];
            routing?: components["schemas"]["Routing"];
            visibility?: components["schemas"]["Visibility"];
            /** @description Roles permitted to see/activate the app. Empty = all members. */
            roles?: string[];
        };
        /** @description A registered app — its server-managed state plus its manifest. */
        App: {
            slug: components["schemas"]["Slug"];
            status: components["schemas"]["AppStatus"];
            mode: components["schemas"]["AppMode"];
            builtin: boolean;
            /**
             * Format: uuid
             * @description Owning org, or null for platform-global apps.
             */
            organizationId?: string | null;
            manifest: components["schemas"]["AppManifest"];
            /** @description Latest heartbeat-derived health, or null if unknown. */
            isHealthy?: boolean | null;
            /** Format: date-time */
            lastSeenAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RegisterAppRequest: {
            manifest: components["schemas"]["AppManifest"];
            /**
             * Format: uuid
             * @description Owning org for org-scoped apps; omit for platform-global.
             */
            organizationId?: string | null;
        };
        HeartbeatRequest: {
            /**
             * @default online
             * @enum {string}
             */
            status: "online" | "degraded";
            /** @description Free-form app-reported metadata (version, build, etc). */
            metadata?: {
                [key: string]: unknown;
            };
        };
        Error: {
            /** @description Stable machine-readable error code */
            error: string;
            /** @description Human-readable detail */
            message?: string;
        };
        ValidationErrorBody: {
            /** @enum {string} */
            error: "validation_error";
            message?: string;
            fields: {
                path: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description Missing or invalid session / token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The caller lacks the required scope for this object. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description App not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request body / manifest failed validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationErrorBody"];
            };
        };
        /** @description Unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description The app's immutable url-safe slug (e.g. `clock`). */
        Slug: components["schemas"]["Slug"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listApps: {
        parameters: {
            query?: {
                /** @description Filter by lifecycle status. Omit for all non-suspended. */
                status?: components["schemas"]["AppStatus"];
                /** @description Filter by app mode (portal | standalone). */
                mode?: components["schemas"]["AppMode"];
                limit?: number;
                /** @description Opaque pagination cursor returned as `nextCursor`. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The page of apps visible to the caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apps: components["schemas"]["App"][];
                        /** @description Cursor for the next page, or null if last page. */
                        nextCursor?: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    registerApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterAppRequest"];
            };
        };
        responses: {
            /** @description App registered (status = registered). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description An app with this slug already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The app's immutable url-safe slug (e.g. `clock`). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The app. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The app's immutable url-safe slug (e.g. `clock`). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppManifest"];
            };
        };
        responses: {
            /** @description Updated app. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The app's immutable url-safe slug (e.g. `clock`). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Forbidden, or the app is built-in and cannot be deleted. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    activateApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The app's immutable url-safe slug (e.g. `clock`). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description App activated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    suspendApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The app's immutable url-safe slug (e.g. `clock`). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description App suspended. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    heartbeatApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The app's immutable url-safe slug (e.g. `clock`). */
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description Heartbeat accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accepted: boolean;
                        /** Format: date-time */
                        at: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
