#!/usr/bin/env node
/* ============================================================
   FuzeFront Design System — build script
   Scans the folder and (re)generates:
     - _ds_manifest.json  (components, cards, tokens, css entry points)
     - index.js           (ESM re-exports — the public import surface)
     - _ds_bundle.js      (optional; only if esbuild is installed)
   Run:  node design-system/build.mjs
   ============================================================ */
import {
  readFileSync, writeFileSync, readdirSync, existsSync, statSync,
} from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, relative, basename, posix } from 'node:path'

const ROOT = dirname(fileURLToPath(import.meta.url))
const NAMESPACE = 'FuzeFrontDesignSystem'

const rel = (p) => relative(ROOT, p).split('\\').join('/')

function walk(dir, pred, out = []) {
  if (!existsSync(dir)) return out
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    if (statSync(full).isDirectory()) walk(full, pred, out)
    else if (pred(name)) out.push(full)
  }
  return out
}

/* ---- Components ----------------------------------------------------------- */
const componentFiles = walk(join(ROOT, 'components'), (n) => n.endsWith('.jsx'))
  .sort()
const components = componentFiles.map((f) => ({
  name: basename(f, '.jsx'),
  sourcePath: rel(f),
}))

/* ---- Cards (guideline + category specimens) ------------------------------ */
const cardFiles = [
  ...walk(join(ROOT, 'guidelines'), (n) => n.endsWith('.card.html')),
  ...walk(join(ROOT, 'components'), (n) => n.endsWith('.card.html')),
].sort()
const ATTR = (s, k) => (s.match(new RegExp(`${k}="([^"]*)"`)) || [])[1] || ''
const cards = cardFiles.map((f) => {
  const head = readFileSync(f, 'utf8').split('\n')[0]
  return {
    path: rel(f),
    group: ATTR(head, 'group'),
    viewport: ATTR(head, 'viewport'),
    name: ATTR(head, 'name'),
    subtitle: ATTR(head, 'subtitle'),
  }
})

/* ---- Tokens -------------------------------------------------------------- */
const TOKEN_CSS = ['tokens/colors.css', 'tokens/typography.css', 'tokens/spacing.css']
function kindOf(name, value) {
  if (/shadow/.test(name)) return 'shadow'
  if (/radius/.test(name)) return 'radius'
  if (/seam|color|bg-|surface|border-color|border-strong|accent|indigo|cyan|mint|amber|coral|graphite|paper|ink|line|background|foreground|ring|destructive|primary|secondary|muted|card|popover|--success|--warning|--error/.test(name)) {
    return /font|text-|weight|leading|tracking|family/.test(name) ? 'font' : 'color'
  }
  if (/font|weight|leading|tracking|--text-|role-/.test(name)) return 'font'
  if (/space|width|height|container|gutter|--top-bar|--side-panel/.test(name)) return 'spacing'
  if (/duration|ease/.test(name)) return 'other'
  if (/#|rgb|hsl|gradient/.test(value)) return 'color'
  return 'other'
}
const seen = new Set()
const tokens = []
for (const cssRel of TOKEN_CSS) {
  const file = join(ROOT, cssRel)
  if (!existsSync(file)) continue
  const css = readFileSync(file, 'utf8')
  const re = /(--[\w-]+)\s*:\s*([^;]+);/g
  let m
  while ((m = re.exec(css))) {
    const name = m[1].trim()
    if (seen.has(name)) continue
    seen.add(name)
    tokens.push({ name, value: m[2].trim(), kind: kindOf(name, m[2]), definedIn: cssRel })
  }
}

/* ---- Manifest ------------------------------------------------------------ */
const manifest = {
  namespace: NAMESPACE,
  components,
  cards,
  templates: [],
  globalCssPaths: [
    'tokens/fonts.css', 'tokens/colors.css', 'tokens/typography.css',
    'tokens/spacing.css', 'tokens/base.css', 'styles.css',
  ],
  tokens,
  themes: [
    { name: 'dark', selector: ":root, [data-theme=dark]", default: true },
    { name: 'light', selector: "[data-theme=light]" },
  ],
  brandFonts: [
    { family: 'Space Grotesk', status: 'ok', tokens: ['--font-display'], path: 'tokens/typography.css' },
    { family: 'Inter', status: 'ok', tokens: ['--font-sans'], path: 'tokens/typography.css' },
    { family: 'JetBrains Mono', status: 'ok', tokens: ['--font-mono'], path: 'tokens/typography.css' },
  ],
  source: 'code',
}
writeFileSync(join(ROOT, '_ds_manifest.json'), JSON.stringify(manifest, null, 2) + '\n')

/* ---- index.js (public ESM re-exports) ------------------------------------ */
const indexLines = [
  '/* AUTO-GENERATED by build.mjs — do not edit. The public import surface.',
  "   Consumers: import { Button, AppCard } from 'fuzefront-design-system'", '*/',
  ...components.map((c) => `export { ${c.name} } from './${posix.normalize(c.sourcePath)}'`),
  '',
]
writeFileSync(join(ROOT, 'index.js'), indexLines.join('\n'))

/* ---- Optional bundle (only if esbuild is available) ---------------------- */
let bundled = false
try {
  const esbuild = await import('esbuild')
  await esbuild.build({
    entryPoints: [join(ROOT, 'index.js')],
    bundle: true,
    format: 'iife',
    globalName: NAMESPACE,
    outfile: join(ROOT, '_ds_bundle.js'),
    jsx: 'automatic',
    external: ['react', 'react-dom'],
    logLevel: 'silent',
  })
  bundled = true
} catch {
  /* esbuild not installed — index.js is the consumable; cards are static. */
}

console.log(
  `DS build: ${components.length} components, ${cards.length} cards, ${tokens.length} tokens` +
  (bundled ? ' + _ds_bundle.js' : ' (skipped _ds_bundle.js: run `npm i -D esbuild` to enable)')
)
