// Unified app-registry authentication: pre-shared consumer token OR JWT session.
//
// The app-registry is called by TWO different kinds of caller and both must work
// on every route:
//
//   1. CONSUMER PRODUCTS (FuzeHub, FuzeSales, …) running `register.sh` as a
//      Kubernetes init container. They have no human, no OIDC session, and no way
//      to obtain a JWT — they present the pre-shared CONSUMER_REGISTRATION_SECRET
//      as a Bearer token. A match is treated as a platform-admin service call
//      (isPlatformAdmin: true via resolveCaller), so Permit checks are bypassed.
//
//   2. HUMANS / ADMIN UI, carrying an Authentik-issued JWT, validated by
//      authenticateToken from @fuzefront/core.
//
// Order matters: the constant-time consumer-secret comparison runs FIRST and only
// falls through to JWT validation on a miss, so a JWT caller is never charged the
// secret comparison's failure path and a consumer never hits JWKS.
//
// WHY THIS IS ON EVERY ROUTE, NOT JUST POST /apps. register.sh's FIRST call is
// `GET /apps/:slug` (the idempotency probe: 200 = already registered, 404 =
// register now) and it re-PUTs the manifest on every redeploy so manifest edits
// are not frozen at first registration. It also PUTs policy.json and
// billing-profile.json. With the consumer token accepted on only POST /apps and
// POST /apps/:slug/activate, the probe 401s and the script's `401|403) die` arm
// CrashLoopBackOffs the consumer's pod before it ever reaches the register call.
//
// FAILS CLOSED, DELIBERATELY, ON A CONSUMER-SHAPED TOKEN.
//
// This used to have a FAIL-SAFE (really fail-OPEN) behaviour: when
// CONSUMER_REGISTRATION_SECRET was unset, or the presented token simply didn't
// match it, the request silently fell through to authenticateToken, which then
// rejected it with a generic "Invalid token." 401 from jwt.verify — a message
// that gives an operator staring at a CrashLoopBackOff pod zero signal that the
// *server* has no registration secret configured, or that the token it received
// doesn't match. That ambiguity cost real debugging time (see
// docs/mfe-self-registration.md "Diagnosing a 401").
//
// To fail closed instead, this distinguishes a consumer-secret ATTEMPT from a
// JWT attempt by shape rather than by whether the comparison happens to
// succeed: a JWT is always three dot-separated segments
// (header.payload.signature); the pre-shared secret is generated by
// `openssl rand -hex 32` (see docs/mfe-self-registration.md) and is a flat hex
// string with no dots. A bearer token that isn't JWT-shaped is therefore never
// handed to authenticateToken — it either matches CONSUMER_REGISTRATION_SECRET
// or the request is rejected right here, with a log line that names exactly
// what to check (the secret is unset on this pod vs. the token doesn't match).
import type { Request, Response, NextFunction } from 'express'
import { authenticateToken } from './auth'

/** A JWT is always header.payload.signature — exactly two '.' separators. */
function looksLikeJwt(token: string): boolean {
  return token.split('.').length === 3
}

// Shaped to satisfy @fuzefront/core's User. `email` is required there; this
// caller is a service, not a person, so it carries a non-routable sentinel
// address rather than anything that could collide with a real account.
//
// `id` is DELIBERATELY NOT A UUID — there is no `users` row for a service — and
// that is load-bearing rather than incidental. Anything that treats this id as a
// real user id and puts it in a query against a `uuid` column will throw
// `invalid input syntax for type uuid` in Postgres. `users.id`,
// `organization_memberships.user_id` and friends are all `table.uuid(...)`.
//
// It is exported so the one place that needs to know — resolveCaller — can
// recognise the service caller by identity instead of by shape-guessing, and so
// this coupling is greppable rather than implicit.
export const SYNTHETIC_CONSUMER_USER_ID = 'consumer-registration'

const SYNTHETIC_CONSUMER_USER = {
  id: SYNTHETIC_CONSUMER_USER_ID,
  email: 'consumer-registration@fuzefront.invalid',
  roles: ['admin'] as string[],
}

/**
 * Length-independent constant-time-ish comparison. Returning early on a length
 * mismatch leaks only the length, which is not secret; the byte loop below does
 * not short-circuit, so a correct prefix is not distinguishable by timing.
 */
function safeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i)
  return diff === 0
}

export function authenticateConsumerOrSession(
  req: Request & { user?: unknown },
  res: Response,
  next: NextFunction
): void {
  const auth = req.headers.authorization
  const bearer = auth?.startsWith('Bearer ') ? auth.slice(7) : undefined

  if (bearer !== undefined && !looksLikeJwt(bearer)) {
    // This is not JWT-shaped, so it can only be an attempted consumer
    // registration call — never let it fall through to authenticateToken,
    // which would reject it with an unrelated "Invalid token." error and hide
    // the real cause from whoever is debugging the consumer's pod.
    const secret = process.env.CONSUMER_REGISTRATION_SECRET
    if (!secret) {
      console.error(
        '[consumer-auth] Rejected a consumer-registration attempt: ' +
          'CONSUMER_REGISTRATION_SECRET is not set on this pod. Seal the ' +
          'secret into fuzefront-secrets and confirm ' +
          'deploy/helm/fuzefront/values-prod.yaml sets ' +
          'secret.consumerRegistrationSecret (see docs/mfe-self-registration.md).'
      )
      res.status(503).json({
        error: 'consumer_registration_unavailable',
        message:
          'Consumer registration is not configured on this server ' +
          '(CONSUMER_REGISTRATION_SECRET is unset). This is a platform ' +
          'configuration gap, not a caller credential problem.',
      })
      return
    }
    if (!safeEqual(bearer, secret)) {
      console.error(
        '[consumer-auth] Rejected a consumer-registration attempt: bearer ' +
          "token does not match this server's CONSUMER_REGISTRATION_SECRET. " +
          'Verify the caller is sending the same value the platform sealed ' +
          '(consumers set it as FUZEFRONT_REGISTRATION_TOKEN — see ' +
          'docs/mfe-self-registration.md).'
      )
      res.status(401).json({
        error: 'invalid_registration_token',
        message:
          "Bearer token does not match this server's registration secret.",
      })
      return
    }
    req.user = SYNTHETIC_CONSUMER_USER
    next()
    return
  }

  // JWT-shaped bearer token, or no Authorization header at all → ordinary
  // session auth. authenticateToken returns a Response when it rejects; this
  // middleware's contract is void, so the result is deliberately discarded.
  void authenticateToken(req as any, res, next)
}
