{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "fuzefront-secrets",
    "namespace": "fuzefront",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "fuzefront-secrets",
        "namespace": "fuzefront",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "GOOGLE_CLIENT_ID": "AgA5VyykueHXhXl3AC+pWP9N0hriKqf8k3oGznMp8lR4tVljGaQie1IPykdj6k4ZOxMl5PV3DY4y7b0CqiyMBt1pO+a6wDfHyOE13kgyBqgiEAMZs9pZ8QJjXM5FlxexKcpMXodE47Pb+2jO+lyRL9lvqVWVH+kDmfO8/BntIp8P35j+n1mj2OW4nx+kjMcuOP1jIgKTjvkyZmAfI9hCz/uUPskDFPAUBG6HsR1Kl+4Kq/7e7GZMNOcIOgwVly/bJRtpU6WqJpbguyTgkudq+ZcXRownvnn/ExueacsbAO9tKgLaZBaVylOWVdktUgpNcAflTnhdRVOpxg9Mdp5Q9hg1awm4N1W0Pw7kGHfnHv93SiRvZTIdr40RIRyPDjFzN5WbvACDVkWnRpJRXP+zRLyBdU6iyRb3zDS8oez8MXrQUmiNfirfaLv4/Fxtc2dGnJUjr9Drwo1G9AEc4SfXtwT0+O0t/riXQnIVllzoFKagwU6wRx8nkUW3vYobUTiPEbLV2mlUQyqFSztc4DcQBf5PMQNRCuRgXyCB+aj/q3tI/B+lJfIk2hA2t7NOyZRBeHPJ5Tf9GQenG9fB//nYSsEBtUKgA8PZKYuRN1DXCZruIr28XXNKdIqbX3sBfAqcf3LVDOeWvKbSywkd9ZYIBwepzmfsmkJZbDuCIKeOomWM5xhx5aLsiI50yxHnXHLlBbdVq3zUadHp0/fK1hGgEhJRaX0g2DEOgYScN2BBEha/kElR4vDDyq7B6q73CyEQSMADPb0lKi8KMYjYsZgY6Yz/3OKdTkix8Sk=",
      "GOOGLE_CLIENT_SECRET": "AgCST7gOkQGDOzjOed8t8of1oFXXDytCoc3eCgT5oF4oI1AEloo5Rs2PNdYjvuhpByHYy+oy9kFrNVlbpIJ+zDUIFpF87mTOMGikoXHj7AAWeEe3MIU5RhJyr9mGlU1tIHFqGy5ginwqgnfylYOLDl9k9mPNWcOYK0WSrhrsJP38+R9HBNPZi2fLROCkK3OlvjbGE5pOJbgdQABG9R5asPkuKsVdmsZEeV981G9BUuFtlJRkqbyC2LJJE4V3ELRt8zirtjtVT2IwpsvMMAzvOFXqvfSSCmXAp/2gZ//ItfIGZ2z58DiMk2hRKjce85c/p17oMmyIqUNnfnkaGuA93oBJve6I4SrnQCv1oKjLXjbXwGMVda2HB4I5HwmyUKut7mIKr1/3lHeUIBzjxkw7lg9pgxCbpMIgL/7RR7Ma/3aKaBLvuKjXCD/1/SYfSiL9USKgd6SJi11OssniibN07qTqrelzodpwAIS1fyK3gMGEiJYK7bssmQieiLnO87V+mZO1HUSNdQbYY1Of8Jq+MN9a6mrIw0HzDH11y4fLX9sTQwlDMxnUSk/D3nmkrTfjCZF+5jNI1RTI8pkohsvK9m1RY9uUQcznV2r1Bhf/qMoskjbtU2yB1N6kSd81ENYXxBiR2JqpdzC8vTMRctRO8C3L2CnU0cYWuBv0ZJ+Ea+yfIcxsaNv73q10kHaqfh18RWqQDH4Qq5QlRm+NO4gDph6m2mgNVytdDpoSLyCt6MWhk4Glmg=="
    }
  }
}
