/** A publisher agent prepares a provider-specific review packet. It never submits it. */
export type SubmissionMode = 'console-review' | 'partner-contact' | 'no-public-route-confirmed';
export type PublisherDefinition = Readonly<{
  providerId: string;
  agentId: string;
  target: string;
  consoleUrl: string;
  documentationUrl: string;
  mode: SubmissionMode;
  qualifyingSurface: string;
  metadata: readonly string[];
  checks: readonly string[];
  review: string;
  handoff: string;
}>;

const commonMetadata = ['appName', 'shortDescription', 'longDescription', 'logoUrl', 'supportUrl', 'privacyPolicyUrl', 'termsUrl', 'contactEmail', 'screenshots'] as const;
const commonChecks = ['HTTPS redirect and landing URLs', 'live privacy and support links', 'scope to feature mapping', 'install, uninstall and account deletion test', 'reviewer test account and instructions', 'no secrets in evidence'] as const;
const google = (providerId: string, surface: string): PublisherDefinition => ({providerId, agentId: `${providerId}-marketplace-publisher`, target: 'Google Workspace Marketplace', consoleUrl: 'https://console.cloud.google.com/apis/library/appsmarket-component.googleapis.com', documentationUrl: 'https://developers.google.com/workspace/marketplace/how-to-publish', mode: 'console-review', qualifyingSurface: surface, metadata: [...commonMetadata, 'OAuth consent screen', 'host product configuration', 'listing language and categories'], checks: [...commonChecks, 'OAuth verification where required', 'Marketplace SDK configured', 'public listing review prerequisites'], review: 'Google reviews public listings; an OAuth client alone does not constitute a Marketplace app.', handoff: 'Workspace Marketplace listing draft and OAuth verification evidence'});
const microsoft = (providerId: string, surface: string, doc: string): PublisherDefinition => ({providerId, agentId: `${providerId}-marketplace-publisher`, target: 'Microsoft Marketplace', consoleUrl: 'https://partner.microsoft.com/dashboard/marketplace-offers/overview', documentationUrl: doc, mode: 'console-review', qualifyingSurface: surface, metadata: [...commonMetadata, 'publisher legal profile', 'app package or manifest', 'offer category', 'validation instructions'], checks: [...commonChecks, 'Partner Center enrollment', 'manifest validation', 'Microsoft certification policy review'], review: 'Partner Center certification and marketplace approval; a Graph OAuth connector by itself is not a store app.', handoff: 'Partner Center offer draft with validated package and certification notes'});
const partner = (providerId: string, target: string, consoleUrl: string, documentationUrl: string, qualifyingSurface: string, mode: SubmissionMode): PublisherDefinition => ({providerId, agentId: `${providerId}-marketplace-publisher`, target, consoleUrl, documentationUrl, mode, qualifyingSurface, metadata: [...commonMetadata, 'qualifying app installation instructions', 'reviewer test account'], checks: [...commonChecks, 'provider-specific eligibility and security review', 'installation and removal evidence', 'provider confirmation of publication'], review: 'API access to this provider is not itself a store app. Verify a qualifying integration and the current submission route.', handoff: 'Provider listing review packet and approval evidence'});

export const publisherDefinitions: readonly PublisherDefinition[] = [
  google('google-drive', 'Google Workspace Drive app or Workspace add-on with an actual Drive user interface'),
  google('google-calendar', 'Google Workspace add-on or supported web app integration with Calendar user interface'),
  google('google-contacts', 'Qualifying Google Workspace add-on or web app; People API OAuth access alone is insufficient'),
  microsoft('microsoft-outlook', 'Outlook add-in with Office add-in manifest', 'https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish-office-add-ins-to-appsource'),
  microsoft('microsoft-onedrive', 'Qualifying Microsoft 365 app or SaaS marketplace offer; Graph file access alone is insufficient', 'https://learn.microsoft.com/en-us/partner-center/marketplace-offers/add-in-submission-guide'),
  {...microsoft('microsoft-teams', 'Teams app package with valid Teams manifest', 'https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/publish'), target: 'Microsoft Teams Store', checks: [...commonChecks, 'Teams app manifest validation', 'Teams Store validation guidelines']},
  {providerId: 'slack', agentId: 'slack-marketplace-publisher', target: 'Slack Marketplace', consoleUrl: 'https://api.slack.com/apps', documentationUrl: 'https://api.slack.com/start/distributing/directory', mode: 'console-review', qualifyingSurface: 'Distributable Slack app with OAuth installation and useful Slack functionality', metadata: [...commonMetadata, 'OAuth scopes', 'install URL', 'demo video or reviewer walkthrough'], checks: [...commonChecks, 'Slack Marketplace app guidelines', 'OAuth install in independent workspace', 'request only necessary scopes'], review: 'Submit from Slack app configuration; Slack reviews listing and app.', handoff: 'Slack app listing draft and install walkthrough'},
  {providerId: 'notion', agentId: 'notion-marketplace-publisher', target: 'Notion Marketplace Connections', consoleUrl: 'https://www.notion.so/profile/integrations', documentationUrl: 'https://developers.notion.com/guides/get-started/marketplace-listing', mode: 'console-review', qualifyingSurface: 'Public Notion connection using OAuth 2.0', metadata: [...commonMetadata, 'connection category', 'OAuth redirect URL'], checks: [...commonChecks, 'public connection OAuth flow', 'Notion listing guidance'], review: 'Create connection listing in Marketplace dashboard and submit for Notion review.', handoff: 'Notion connection listing draft and OAuth install evidence'},
  {providerId: 'github', agentId: 'github-marketplace-publisher', target: 'GitHub Marketplace', consoleUrl: 'https://github.com/settings/apps', documentationUrl: 'https://docs.github.com/en/apps/github-marketplace/listing-an-app-on-github-marketplace', mode: 'console-review', qualifyingSurface: 'Public GitHub App; OAuth Apps alone are not GitHub Marketplace Apps', metadata: [...commonMetadata, 'GitHub App permissions', 'pricing plan', 'listing images'], checks: [...commonChecks, 'GitHub App public visibility', 'Marketplace listing requirements', 'verified publisher for paid plans'], review: 'Request publish from draft listing; GitHub onboarding expert reviews.', handoff: 'GitHub Marketplace listing draft and permission justification'},
  {providerId: 'dropbox', agentId: 'dropbox-marketplace-publisher', target: 'Dropbox App Center', consoleUrl: 'https://www.dropbox.com/developers/apps', documentationUrl: 'https://developers.dropbox.com/oauth-guide', mode: 'no-public-route-confirmed', qualifyingSurface: 'Dropbox production app; App Center inclusion requires a provider-confirmed route', metadata: [...commonMetadata, 'Dropbox app key', 'production status', 'permission scope justification'], checks: [...commonChecks, 'Dropbox production approval', 'OAuth scoped access', 'confirm App Center submission path with Dropbox'], review: 'No public self-service App Center listing submission route confirmed in official developer documentation.', handoff: 'Production app and App Center inquiry packet; obtain Dropbox confirmation before claiming listing'},
  google('google-gmail', 'Gmail add-on or Google Workspace app with a qualifying Gmail user interface'),
  google('google-sheets', 'Sheets Editor add-on, Workspace add-on, or integrated web app; Sheets API access alone is insufficient'),
  google('google-docs', 'Docs Editor add-on, Workspace add-on, or integrated web app; Docs API access alone is insufficient'),
  google('google-slides', 'Slides Editor add-on, Workspace add-on, or integrated web app; Slides API access alone is insufficient'),
  google('google-tasks', 'Qualifying Workspace add-on or integrated web app; Tasks API access alone is insufficient'),
  microsoft('microsoft-sharepoint', 'Modern SharePoint Framework solution or qualifying Microsoft 365 app offer; retired SharePoint Add-ins are not eligible', 'https://learn.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-overview'),
  microsoft('microsoft-todo', 'Qualifying Microsoft 365 app or SaaS offer; Graph To Do access alone is insufficient', 'https://learn.microsoft.com/en-us/partner-center/marketplace-offers/create-new-saas-offer'),
  {providerId: 'jira-cloud', agentId: 'jira-cloud-marketplace-publisher', target: 'Atlassian Marketplace', consoleUrl: 'https://marketplace.atlassian.com/manage', documentationUrl: 'https://developer.atlassian.com/platform/marketplace/creating-a-marketplace-listing/', mode: 'console-review', qualifyingSurface: 'Qualifying Jira Cloud Forge app; OAuth API access alone is insufficient', metadata: [...commonMetadata, 'Forge app ID', 'Jira scopes', 'hosting and data residency details'], checks: [...commonChecks, 'Forge app deployment and installation', 'Atlassian Marketplace guidelines', 'cloud security and privacy requirements'], review: 'Submit the Forge app listing for Atlassian Marketplace review; new Connect app publication is closed.', handoff: 'Jira Forge app listing draft and installation evidence'},
  {providerId: 'confluence-cloud', agentId: 'confluence-cloud-marketplace-publisher', target: 'Atlassian Marketplace', consoleUrl: 'https://marketplace.atlassian.com/manage', documentationUrl: 'https://developer.atlassian.com/platform/marketplace/creating-a-marketplace-listing/', mode: 'console-review', qualifyingSurface: 'Qualifying Confluence Cloud Forge app; OAuth API access alone is insufficient', metadata: [...commonMetadata, 'Forge app ID', 'Confluence scopes', 'hosting and data residency details'], checks: [...commonChecks, 'Forge app deployment and installation', 'Atlassian Marketplace guidelines', 'cloud security and privacy requirements'], review: 'Submit the Forge app listing for Atlassian Marketplace review; new Connect app publication is closed.', handoff: 'Confluence Forge app listing draft and installation evidence'},
  {providerId: 'linear', agentId: 'linear-marketplace-publisher', target: 'Linear Integrations Directory', consoleUrl: 'https://linear.app/developers/integration-directory', documentationUrl: 'https://linear.app/developers/integration-directory', mode: 'console-review', qualifyingSurface: 'Public OAuth integration with useful Linear functionality', metadata: [...commonMetadata, 'OAuth integration ID', 'requested permissions', 'installation walkthrough'], checks: [...commonChecks, 'public OAuth installation', 'Linear directory submission criteria'], review: 'Follow the Linear Integration Directory submission process and wait for Linear confirmation.', handoff: 'Linear directory listing draft and OAuth installation evidence'},
  {providerId: 'trello', agentId: 'trello-marketplace-publisher', target: 'Trello Power-Up Directory', consoleUrl: 'https://trello.com/power-ups/admin', documentationUrl: 'https://developer.atlassian.com/cloud/trello/guides/power-ups/submitting-your-power-up/', mode: 'partner-contact', qualifyingSurface: 'Qualifying Trello Power-Up; API token access alone is insufficient', metadata: [...commonMetadata, 'Power-Up ID', 'capabilities', 'installation walkthrough'], checks: [...commonChecks, 'Power-Up functionality and review criteria', 'Trello developer support submission'], review: 'Submit through the Trello developer support process; await directory approval.', handoff: 'Trello Power-Up listing and support submission packet'},
  partner('openai', 'ChatGPT app directory', 'https://platform.openai.com/apps', 'https://help.openai.com/en/articles/12515353-build-with-the-apps-sdk', 'ChatGPT Apps SDK app with a qualifying user-facing experience', 'console-review'),
  partner('anthropic', 'Claude Connectors Directory', 'https://claude.ai/directory/manage', 'https://claude.com/docs/connectors/building/submission', 'Production remote MCP server meeting Claude directory requirements', 'console-review'),
  partner('gemini', 'Gemini integration route unconfirmed', 'https://ai.google.dev/', 'https://ai.google.dev/', 'Provider-confirmed Gemini app integration surface', 'no-public-route-confirmed'),
  partner('base44', 'Base44 integration route unconfirmed', 'https://base44.com/', 'https://docs.base44.com/', 'Provider-confirmed Base44 extension surface', 'no-public-route-confirmed'),
  partner('vercel', 'Vercel Marketplace', 'https://vercel.com/integrations', 'https://vercel.com/docs/integrations/create-integration/submit-integration', 'Vercel Marketplace integration with installation and provider API support', 'console-review'),
  partner('lovable', 'Lovable integration route unconfirmed', 'https://lovable.dev/', 'https://docs.lovable.dev/', 'Provider-confirmed Lovable extension surface', 'no-public-route-confirmed'),
  partner('replit', 'Replit integration route unconfirmed', 'https://replit.com/', 'https://docs.replit.com/platforms/mcp-server', 'Provider-confirmed Replit app listing surface', 'no-public-route-confirmed'),
] as const;

export const getPublisher = (providerId: string): PublisherDefinition | undefined => publisherDefinitions.find(item => item.providerId === providerId);
export type ListingInput = Readonly<Record<string, unknown>>;
export type HandoffPacket = Readonly<{providerId: string; agentId: string; target: string; submissionMode: SubmissionMode; ready: boolean; missing: readonly string[]; checks: readonly string[]; evidence: Readonly<Record<string, unknown>>; handoff: string; documentationUrl: string}>;
/** Builds a local review artifact; caller must explicitly complete the provider's review flow. */
export function prepareHandoff(providerId: string, input: ListingInput): HandoffPacket {
  const publisher = getPublisher(providerId);
  if (!publisher) throw new Error(`Unknown publisher: ${providerId}`);
  const missing = publisher.metadata.filter(key => key === 'screenshots'
    ? !Array.isArray(input[key]) || !(input[key] as unknown[]).some(item => typeof item === 'string' && item.trim())
    : typeof input[key] !== 'string' || !(input[key] as string).trim());
  return {providerId, agentId: publisher.agentId, target: publisher.target, submissionMode: publisher.mode, ready: missing.length === 0 && publisher.mode !== 'no-public-route-confirmed', missing, checks: publisher.checks, evidence: input, handoff: publisher.handoff, documentationUrl: publisher.documentationUrl};
}
