import type { Resource } from 'i18next'

/**
 * Bundles the build-time locale JSON into the i18next `Resource` shape the
 * `@fuzefront/i18n` provider consumes:
 *
 *   { en: { common: {...} }, he: { common: {...} }, ... }
 *
 * The JSON lives in `frontend/locales/<lng>/<namespace>.json` — inside the
 * frontend Docker build context so it is bundled deterministically — and is the
 * source of truth regenerated by the `@fuzefront/i18n-translate` workflow.
 * English is hand-maintained; the rest are AI-translated. We glob *eagerly* so
 * the strings are inlined into the bundle — no async locale fetch at runtime.
 */
const modules = import.meta.glob('../../locales/**/*.json', {
  eager: true,
}) as Record<string, { default: Record<string, unknown> }>

export const resources: Resource = (() => {
  const out: Resource = {}
  for (const [path, mod] of Object.entries(modules)) {
    // path looks like ".../locales/en/common.json"
    const match = path.match(/\/locales\/([^/]+)\/([^/]+)\.json$/)
    if (!match) continue
    const [, lng, namespace] = match
    out[lng] ??= {}
    ;(out[lng] as Record<string, unknown>)[namespace] = mod.default
  }
  return out
})()

/** Languages we actually shipped strings for (have at least one namespace bundled). */
export const bundledLanguages = Object.keys(resources)
